
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Entity
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class Monster : Luban.BeanBase
{
    public Monster(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Asset = _buf.ReadString();
        AnimGroup = _buf.ReadInt();
        AI = _buf.ReadInt();
        SearchRange = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);SkillList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); SkillList.Add(_e0);}}
        MoveSpeed = _buf.ReadInt();
        Hp = _buf.ReadInt();
        Ammo = _buf.ReadInt();
        Attack = _buf.ReadInt();
        ActionSpeed = _buf.ReadInt();
        BodyRadius = global::cfg.Fix.DeserializeFix(_buf);
        HitRadius = global::cfg.Fix.DeserializeFix(_buf);
        Stamina = _buf.ReadInt();
    }

    public static Monster DeserializeMonster(ByteBuf _buf)
    {
        return new Entity.Monster(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 资源
    /// </summary>
    public readonly string Asset;
    /// <summary>
    /// 动画组
    /// </summary>
    public readonly int AnimGroup;
    /// <summary>
    /// AI组
    /// </summary>
    public readonly int AI;
    /// <summary>
    /// 搜索范围
    /// </summary>
    public readonly int SearchRange;
    /// <summary>
    /// 该怪物拥有的技能ID
    /// </summary>
    public readonly System.Collections.Generic.List<int> SkillList;
    /// <summary>
    /// 初始移动速度
    /// </summary>
    public readonly int MoveSpeed;
    /// <summary>
    /// 初始血量
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 弹仓，相当于mp
    /// </summary>
    public readonly int Ammo;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 行动速度，和移动速度不同，他是增加角色行动速度，也就是变化timeline和动画播放的scale的，比如wow里面开嗜血就是加行动速度
    /// </summary>
    public readonly int ActionSpeed;
    /// <summary>
    /// 体型圆形半径，用于移动碰撞的，单位：米
    /// </summary>
    public readonly Fix BodyRadius;
    /// <summary>
    /// 挨打圆形半径，同体型圆形，只是用途不同，用在判断子弹是否命中的时候
    /// </summary>
    public readonly Fix HitRadius;
    /// <summary>
    /// 当前耐力，耐力是一个百分比消耗，实时恢复的概念，所以上限按规则就是100了
    /// </summary>
    public readonly int Stamina;
   
    public const int __ID__ = 140774607;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        BodyRadius?.ResolveRef(tables);
        HitRadius?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "asset:" + Asset + ","
        + "animGroup:" + AnimGroup + ","
        + "AI:" + AI + ","
        + "searchRange:" + SearchRange + ","
        + "skillList:" + Luban.StringUtil.CollectionToString(SkillList) + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "hp:" + Hp + ","
        + "ammo:" + Ammo + ","
        + "attack:" + Attack + ","
        + "actionSpeed:" + ActionSpeed + ","
        + "bodyRadius:" + BodyRadius + ","
        + "hitRadius:" + HitRadius + ","
        + "stamina:" + Stamina + ","
        + "}";
    }
}
}

