
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Entity
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public partial class TbMonster:Tables.IVOFun
{
    private readonly System.Collections.Generic.Dictionary<int, Entity.Monster> _dataMap;
    private readonly System.Collections.Generic.List<Entity.Monster> _dataList;
    
    public TbMonster()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Entity.Monster>();
        _dataList = new System.Collections.Generic.List<Entity.Monster>();
    }	
	
	public void _LoadData(ByteBuf _buf)
    {
       for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Entity.Monster _v;
            _v = global::cfg.Entity.Monster.DeserializeMonster(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Entity.Monster> DataMap => _dataMap;
    public System.Collections.Generic.List<Entity.Monster> DataList => _dataList;

    public Entity.Monster GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Entity.Monster Get(int key) => _dataMap[key];
    public Entity.Monster this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

