
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Chapter
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class MainChapter : Luban.BeanBase
{
    public MainChapter(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MapId = _buf.ReadInt();
    }

    public static MainChapter DeserializeMainChapter(ByteBuf _buf)
    {
        return new Chapter.MainChapter(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 地图
    /// </summary>
    public readonly int MapId;
   
    public const int __ID__ = -1242532877;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "mapId:" + MapId + ","
        + "}";
    }
}
}

