
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Chapter
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public partial class TbMainChapter:Tables.IVOFun
{
    private readonly System.Collections.Generic.Dictionary<int, Chapter.MainChapter> _dataMap;
    private readonly System.Collections.Generic.List<Chapter.MainChapter> _dataList;
    
    public TbMainChapter()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Chapter.MainChapter>();
        _dataList = new System.Collections.Generic.List<Chapter.MainChapter>();
    }	
	
	public void _LoadData(ByteBuf _buf)
    {
       for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Chapter.MainChapter _v;
            _v = global::cfg.Chapter.MainChapter.DeserializeMainChapter(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Chapter.MainChapter> DataMap => _dataMap;
    public System.Collections.Generic.List<Chapter.MainChapter> DataList => _dataList;

    public Chapter.MainChapter GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Chapter.MainChapter Get(int key) => _dataMap[key];
    public Chapter.MainChapter this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

