
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Spawner
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class MonsterSpawner : Luban.BeanBase
{
    public MonsterSpawner(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MonsterId = _buf.ReadInt();
        TriggerX = global::cfg.Fix.DeserializeFix(_buf);
        SpawnX = global::cfg.Fix.DeserializeFix(_buf);
        SpawnY = global::cfg.Fix.DeserializeFix(_buf);
        PatrolMode = _buf.ReadInt();
        PatrolCenterX = global::cfg.Fix.DeserializeFix(_buf);
        PatrolHalfRange = global::cfg.Fix.DeserializeFix(_buf);
        MaxCount = _buf.ReadInt();
    }

    public static MonsterSpawner DeserializeMonsterSpawner(ByteBuf _buf)
    {
        return new Spawner.MonsterSpawner(_buf);
    }

    /// <summary>
    /// 序号
    /// </summary>
    public readonly int Id;
    /// <summary>
    ///  怪物配置id    
    /// </summary>
    public readonly int MonsterId;
    /// <summary>
    /// 玩家X超过此值触发 
    /// </summary>
    public readonly Fix TriggerX;
    /// <summary>
    /// 生成绝对X 
    /// </summary>
    public readonly Fix SpawnX;
    /// <summary>
    /// 生成绝对Y   
    /// </summary>
    public readonly Fix SpawnY;
    /// <summary>
    /// 0=相对生成点，1=绝对
    /// </summary>
    public readonly int PatrolMode;
    /// <summary>
    ///  巡逻中心X    
    /// </summary>
    public readonly Fix PatrolCenterX;
    /// <summary>
    /// 巡逻半程  
    /// </summary>
    public readonly Fix PatrolHalfRange;
    /// <summary>
    /// 一次生成数量 
    /// </summary>
    public readonly int MaxCount;
   
    public const int __ID__ = 1247328692;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        TriggerX?.ResolveRef(tables);
        SpawnX?.ResolveRef(tables);
        SpawnY?.ResolveRef(tables);
        PatrolCenterX?.ResolveRef(tables);
        PatrolHalfRange?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "monsterId:" + MonsterId + ","
        + "triggerX:" + TriggerX + ","
        + "spawnX:" + SpawnX + ","
        + "spawnY:" + SpawnY + ","
        + "patrolMode:" + PatrolMode + ","
        + "patrolCenterX:" + PatrolCenterX + ","
        + "PatrolHalfRange:" + PatrolHalfRange + ","
        + "MaxCount:" + MaxCount + ","
        + "}";
    }
}
}

