
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Spawner
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public partial class TbMonsterSpawner:Tables.IVOFun
{
    private readonly System.Collections.Generic.Dictionary<int, Spawner.MonsterSpawner> _dataMap;
    private readonly System.Collections.Generic.List<Spawner.MonsterSpawner> _dataList;
    
    public TbMonsterSpawner()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Spawner.MonsterSpawner>();
        _dataList = new System.Collections.Generic.List<Spawner.MonsterSpawner>();
    }	
	
	public void _LoadData(ByteBuf _buf)
    {
       for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Spawner.MonsterSpawner _v;
            _v = global::cfg.Spawner.MonsterSpawner.DeserializeMonsterSpawner(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Spawner.MonsterSpawner> DataMap => _dataMap;
    public System.Collections.Generic.List<Spawner.MonsterSpawner> DataList => _dataList;

    public Spawner.MonsterSpawner GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Spawner.MonsterSpawner Get(int key) => _dataMap[key];
    public Spawner.MonsterSpawner this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

