
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Core
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class EntityGroupTable : Luban.BeanBase
{
    public EntityGroupTable(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Name = _buf.ReadString();
        ReleaseInterval = _buf.ReadFloat();
        Capacity = _buf.ReadInt();
        ExpireTime = _buf.ReadFloat();
        Priority = _buf.ReadInt();
    }

    public static EntityGroupTable DeserializeEntityGroupTable(ByteBuf _buf)
    {
        return new Core.EntityGroupTable(_buf);
    }

    public readonly int ID;
    public readonly string Name;
    public readonly float ReleaseInterval;
    public readonly int Capacity;
    public readonly float ExpireTime;
    public readonly int Priority;
   
    public const int __ID__ = -1858853055;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "ReleaseInterval:" + ReleaseInterval + ","
        + "Capacity:" + Capacity + ","
        + "ExpireTime:" + ExpireTime + ","
        + "Priority:" + Priority + ","
        + "}";
    }
}
}

