
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Core
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class SoundGroupTable : Luban.BeanBase
{
    public SoundGroupTable(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Name = _buf.ReadString();
        SoundAgentCount = _buf.ReadInt();
        AvoidBeingReplacedBySamePriority = _buf.ReadBool();
        Mute = _buf.ReadBool();
        Volume = _buf.ReadFloat();
    }

    public static SoundGroupTable DeserializeSoundGroupTable(ByteBuf _buf)
    {
        return new Core.SoundGroupTable(_buf);
    }

    public readonly int ID;
    public readonly string Name;
    public readonly int SoundAgentCount;
    public readonly bool AvoidBeingReplacedBySamePriority;
    public readonly bool Mute;
    public readonly float Volume;
   
    public const int __ID__ = -35207505;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "SoundAgentCount:" + SoundAgentCount + ","
        + "AvoidBeingReplacedBySamePriority:" + AvoidBeingReplacedBySamePriority + ","
        + "Mute:" + Mute + ","
        + "Volume:" + Volume + ","
        + "}";
    }
}
}

