
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Core
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public partial class TbUIGroupTable:Tables.IVOFun
{
    private readonly System.Collections.Generic.Dictionary<int, Core.UIGroupTable> _dataMap;
    private readonly System.Collections.Generic.List<Core.UIGroupTable> _dataList;
    
    public TbUIGroupTable()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Core.UIGroupTable>();
        _dataList = new System.Collections.Generic.List<Core.UIGroupTable>();
    }	
	
	public void _LoadData(ByteBuf _buf)
    {
       for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Core.UIGroupTable _v;
            _v = global::cfg.Core.UIGroupTable.DeserializeUIGroupTable(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Core.UIGroupTable> DataMap => _dataMap;
    public System.Collections.Generic.List<Core.UIGroupTable> DataList => _dataList;

    public Core.UIGroupTable GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Core.UIGroupTable Get(int key) => _dataMap[key];
    public Core.UIGroupTable this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

