
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Core
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class UIGroupTable : Luban.BeanBase
{
    public UIGroupTable(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Name = _buf.ReadString();
        Depth = _buf.ReadInt();
    }

    public static UIGroupTable DeserializeUIGroupTable(ByteBuf _buf)
    {
        return new Core.UIGroupTable(_buf);
    }

    public readonly int ID;
    public readonly string Name;
    /// <summary>
    /// 每个组的起始Order,用于控制显示顺序
    /// </summary>
    public readonly int Depth;
   
    public const int __ID__ = -1404592110;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Depth:" + Depth + ","
        + "}";
    }
}
}

