
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class AddBuff : AI.AIAction
{
    public AddBuff(ByteBuf _buf)  : base(_buf) 
    {
        BuffId = _buf.ReadInt();
    }

    public static AddBuff DeserializeAddBuff(ByteBuf _buf)
    {
        return new AI.AddBuff(_buf);
    }

    /// <summary>
    /// buffId
    /// </summary>
    public readonly int BuffId;
   
    public const int __ID__ = 391777454;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "buffId:" + BuffId + ","
        + "}";
    }
}
}

