
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class AIActionDef : Luban.BeanBase
{
    public AIActionDef(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Duration = _buf.ReadFloat();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Conditions = new System.Collections.Generic.List<AI.AICondition>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { AI.AICondition _e0;  _e0 = global::cfg.AI.AICondition.DeserializeAICondition(_buf); Conditions.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Actions = new System.Collections.Generic.List<AI.AIAction>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { AI.AIAction _e0;  _e0 = global::cfg.AI.AIAction.DeserializeAIAction(_buf); Actions.Add(_e0);}}
        SortType = (AI.SortType)_buf.ReadInt();
    }

    public static AIActionDef DeserializeAIActionDef(ByteBuf _buf)
    {
        return new AI.AIActionDef(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// AI行为最大持续时间,无论怎么样都需要,防止卡住到某个Action
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// 条件参数
    /// </summary>
    public readonly System.Collections.Generic.List<AI.AICondition> Conditions;
    /// <summary>
    /// 行为及参数
    /// </summary>
    public readonly System.Collections.Generic.List<AI.AIAction> Actions;
    /// <summary>
    /// 排序类型
    /// </summary>
    public readonly AI.SortType SortType;
   
    public const int __ID__ = -1193352735;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Conditions) { _e?.ResolveRef(tables); }
        foreach (var _e in Actions) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "duration:" + Duration + ","
        + "conditions:" + Luban.StringUtil.CollectionToString(Conditions) + ","
        + "actions:" + Luban.StringUtil.CollectionToString(Actions) + ","
        + "sortType:" + SortType + ","
        + "}";
    }
}
}

