
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public abstract partial class AIAction : Luban.BeanBase
{
    public AIAction(ByteBuf _buf) 
    {
    }

    public static AIAction DeserializeAIAction(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case AI.Follow.__ID__: return new AI.Follow(_buf);
            case AI.RandomUseSkill.__ID__: return new AI.RandomUseSkill(_buf);
            case AI.Flee.__ID__: return new AI.Flee(_buf);
            case AI.AddBuff.__ID__: return new AI.AddBuff(_buf);
            case AI.MoveTo.__ID__: return new AI.MoveTo(_buf);
            case AI.WaitTime.__ID__: return new AI.WaitTime(_buf);
            case AI.Patrol.__ID__: return new AI.Patrol(_buf);
            case AI.UseSkill.__ID__: return new AI.UseSkill(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

