
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public abstract partial class AICondition : Luban.BeanBase
{
    public AICondition(ByteBuf _buf) 
    {
    }

    public static AICondition DeserializeAICondition(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case AI.AIResource.__ID__: return new AI.AIResource(_buf);
            case AI.CheckPosition.__ID__: return new AI.CheckPosition(_buf);
            case AI.CheckEnemyInRange.__ID__: return new AI.CheckEnemyInRange(_buf);
            case AI.CheckCanUseSkill.__ID__: return new AI.CheckCanUseSkill(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

