
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class AIGroupDef : Luban.BeanBase
{
    public AIGroupDef(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AiActionList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AiActionList.Add(_e0);}}
    }

    public static AIGroupDef DeserializeAIGroupDef(ByteBuf _buf)
    {
        return new AI.AIGroupDef(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// AI行为队列
    /// </summary>
    public readonly System.Collections.Generic.List<int> AiActionList;
   
    public const int __ID__ = -231292204;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "aiActionList:" + Luban.StringUtil.CollectionToString(AiActionList) + ","
        + "}";
    }
}
}

