
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class AIResource : AI.AICondition
{
    public AIResource(ByteBuf _buf)  : base(_buf) 
    {
        PropertyType = (Skill.PropertyType)_buf.ReadInt();
        OperatorType = (Skill.Operator)_buf.ReadInt();
        Val = _buf.ReadInt();
        Rate = _buf.ReadBool();
    }

    public static AIResource DeserializeAIResource(ByteBuf _buf)
    {
        return new AI.AIResource(_buf);
    }

    /// <summary>
    /// 资源类型
    /// </summary>
    public readonly Skill.PropertyType PropertyType;
    /// <summary>
    /// 操作类型
    /// </summary>
    public readonly Skill.Operator OperatorType;
    /// <summary>
    /// 数值
    /// </summary>
    public readonly int Val;
    /// <summary>
    /// 数值是否为百分比,如果不是则视为数值来对比
    /// </summary>
    public readonly bool Rate;
   
    public const int __ID__ = -1078692388;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "propertyType:" + PropertyType + ","
        + "operatorType:" + OperatorType + ","
        + "val:" + Val + ","
        + "rate:" + Rate + ","
        + "}";
    }
}
}

