
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class CheckPosition : AI.AICondition
{
    public CheckPosition(ByteBuf _buf)  : base(_buf) 
    {
        OperatorType = (Skill.Operator)_buf.ReadInt();
        Target = global::cfg.Fix3.DeserializeFix3(_buf);
    }

    public static CheckPosition DeserializeCheckPosition(ByteBuf _buf)
    {
        return new AI.CheckPosition(_buf);
    }

    /// <summary>
    /// 操作类型
    /// </summary>
    public readonly Skill.Operator OperatorType;
    /// <summary>
    /// 是否处于这个坐标
    /// </summary>
    public readonly Fix3 Target;
   
    public const int __ID__ = 1737713387;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Target?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "operatorType:" + OperatorType + ","
        + "target:" + Target + ","
        + "}";
    }
}
}

