
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class CheckCanUseSkill : AI.AICondition
{
    public CheckCanUseSkill(ByteBuf _buf)  : base(_buf) 
    {
    }

    public static CheckCanUseSkill DeserializeCheckCanUseSkill(ByteBuf _buf)
    {
        return new AI.CheckCanUseSkill(_buf);
    }

   
    public const int __ID__ = 243451896;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

