
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class Flee : AI.AIAction
{
    public Flee(ByteBuf _buf)  : base(_buf) 
    {
        Distance = global::cfg.Fix.DeserializeFix(_buf);
    }

    public static Flee DeserializeFlee(ByteBuf _buf)
    {
        return new AI.Flee(_buf);
    }

    /// <summary>
    /// 逃离到多少范围算完成
    /// </summary>
    public readonly Fix Distance;
   
    public const int __ID__ = -307200500;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Distance?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "distance:" + Distance + ","
        + "}";
    }
}
}

