
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class MoveTo : AI.AIAction
{
    public MoveTo(ByteBuf _buf)  : base(_buf) 
    {
        Target = global::cfg.Fix3.DeserializeFix3(_buf);
    }

    public static MoveTo DeserializeMoveTo(ByteBuf _buf)
    {
        return new AI.MoveTo(_buf);
    }

    /// <summary>
    /// 坐标
    /// </summary>
    public readonly Fix3 Target;
   
    public const int __ID__ = 1336746706;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Target?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "target:" + Target + ","
        + "}";
    }
}
}

