
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.AI
{ 
    public enum SortType
    {
        /// <summary>
        /// 不做处理
        /// </summary>
        Null = 1,
        /// <summary>
        /// 每次执行完这个AI，放到列表最后
        /// </summary>
        ToLast = 2,
    }

} 

