
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public partial class TbAIGroupDef:Tables.IVOFun
{
    private readonly System.Collections.Generic.Dictionary<int, AI.AIGroupDef> _dataMap;
    private readonly System.Collections.Generic.List<AI.AIGroupDef> _dataList;
    
    public TbAIGroupDef()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, AI.AIGroupDef>();
        _dataList = new System.Collections.Generic.List<AI.AIGroupDef>();
    }	
	
	public void _LoadData(ByteBuf _buf)
    {
       for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            AI.AIGroupDef _v;
            _v = global::cfg.AI.AIGroupDef.DeserializeAIGroupDef(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, AI.AIGroupDef> DataMap => _dataMap;
    public System.Collections.Generic.List<AI.AIGroupDef> DataList => _dataList;

    public AI.AIGroupDef GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public AI.AIGroupDef Get(int key) => _dataMap[key];
    public AI.AIGroupDef this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

