
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public partial class TbAIActionDef:Tables.IVOFun
{
    private readonly System.Collections.Generic.Dictionary<int, AI.AIActionDef> _dataMap;
    private readonly System.Collections.Generic.List<AI.AIActionDef> _dataList;
    
    public TbAIActionDef()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, AI.AIActionDef>();
        _dataList = new System.Collections.Generic.List<AI.AIActionDef>();
    }	
	
	public void _LoadData(ByteBuf _buf)
    {
       for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            AI.AIActionDef _v;
            _v = global::cfg.AI.AIActionDef.DeserializeAIActionDef(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, AI.AIActionDef> DataMap => _dataMap;
    public System.Collections.Generic.List<AI.AIActionDef> DataList => _dataList;

    public AI.AIActionDef GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public AI.AIActionDef Get(int key) => _dataMap[key];
    public AI.AIActionDef this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

