
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class UseSkill : AI.AIAction
{
    public UseSkill(ByteBuf _buf)  : base(_buf) 
    {
        SkillId = _buf.ReadInt();
    }

    public static UseSkill DeserializeUseSkill(ByteBuf _buf)
    {
        return new AI.UseSkill(_buf);
    }

    /// <summary>
    /// 技能ID
    /// </summary>
    public readonly int SkillId;
   
    public const int __ID__ = 228355120;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "skillId:" + SkillId + ","
        + "}";
    }
}
}

