
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class WaitTime : AI.AIAction
{
    public WaitTime(ByteBuf _buf)  : base(_buf) 
    {
        Time = global::cfg.Fix.DeserializeFix(_buf);
    }

    public static WaitTime DeserializeWaitTime(ByteBuf _buf)
    {
        return new AI.WaitTime(_buf);
    }

    /// <summary>
    /// 等待时间
    /// </summary>
    public readonly Fix Time;
   
    public const int __ID__ = 768119048;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Time?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "time:" + Time + ","
        + "}";
    }
}
}

