
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.UI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class GameModule : Luban.BeanBase
{
    public GameModule(ByteBuf _buf) 
    {
        Id = (UI.ModuleType)_buf.ReadInt();
        Entry = _buf.ReadString();
    }

    public static GameModule DeserializeGameModule(ByteBuf _buf)
    {
        return new UI.GameModule(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly UI.ModuleType Id;
    /// <summary>
    /// 入口面板
    /// </summary>
    public readonly string Entry;
   
    public const int __ID__ = -1242305352;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "entry:" + Entry + ","
        + "}";
    }
}
}

