
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.UI
{ 
    public enum ModuleType
    {
        /// <summary>
        /// 主页
        /// </summary>
        Home = 1,
        /// <summary>
        /// 战斗通用
        /// </summary>
        FightCommon = 2,
        /// <summary>
        /// 主战斗
        /// </summary>
        FightMainChapter = 3,
        /// <summary>
        /// 登陆
        /// </summary>
        Login = 4,
    }

} 

