
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.UI
{ 
    public enum RedDotType
    {
        /// <summary>
        /// 主页红点
        /// </summary>
        Home = 1,
        /// <summary>
        /// 主界面任务红点
        /// </summary>
        Task = 2,
        /// <summary>
        /// 邮箱红点
        /// </summary>
        Email = 3,
    }

} 

