
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.UI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class RedDot : Luban.BeanBase
{
    public RedDot(ByteBuf _buf) 
    {
        Id = (UI.RedDotType)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Child = new System.Collections.Generic.List<UI.RedDotType>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { UI.RedDotType _e0;  _e0 = (UI.RedDotType)_buf.ReadInt(); Child.Add(_e0);}}
    }

    public static RedDot DeserializeRedDot(ByteBuf _buf)
    {
        return new UI.RedDot(_buf);
    }

    /// <summary>
    /// 红点类型
    /// </summary>
    public readonly UI.RedDotType Id;
    /// <summary>
    /// 子集红点
    /// </summary>
    public readonly System.Collections.Generic.List<UI.RedDotType> Child;
   
    public const int __ID__ = -319260750;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "child:" + Luban.StringUtil.CollectionToString(Child) + ","
        + "}";
    }
}
}

