
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.UI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public partial class TbGameModule:Tables.IVOFun
{
    private readonly System.Collections.Generic.Dictionary<UI.ModuleType, UI.GameModule> _dataMap;
    private readonly System.Collections.Generic.List<UI.GameModule> _dataList;
    
    public TbGameModule()
    {
        _dataMap = new System.Collections.Generic.Dictionary<UI.ModuleType, UI.GameModule>();
        _dataList = new System.Collections.Generic.List<UI.GameModule>();
    }	
	
	public void _LoadData(ByteBuf _buf)
    {
       for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            UI.GameModule _v;
            _v = global::cfg.UI.GameModule.DeserializeGameModule(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<UI.ModuleType, UI.GameModule> DataMap => _dataMap;
    public System.Collections.Generic.List<UI.GameModule> DataList => _dataList;

    public UI.GameModule GetOrDefault(UI.ModuleType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UI.GameModule Get(UI.ModuleType key) => _dataMap[key];
    public UI.GameModule this[UI.ModuleType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

