
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.UI
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public partial class TbRedDot:Tables.IVOFun
{
    private readonly System.Collections.Generic.Dictionary<UI.RedDotType, UI.RedDot> _dataMap;
    private readonly System.Collections.Generic.List<UI.RedDot> _dataList;
    
    public TbRedDot()
    {
        _dataMap = new System.Collections.Generic.Dictionary<UI.RedDotType, UI.RedDot>();
        _dataList = new System.Collections.Generic.List<UI.RedDot>();
    }	
	
	public void _LoadData(ByteBuf _buf)
    {
       for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            UI.RedDot _v;
            _v = global::cfg.UI.RedDot.DeserializeRedDot(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<UI.RedDotType, UI.RedDot> DataMap => _dataMap;
    public System.Collections.Generic.List<UI.RedDot> DataList => _dataList;

    public UI.RedDot GetOrDefault(UI.RedDotType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UI.RedDot Get(UI.RedDotType key) => _dataMap[key];
    public UI.RedDot this[UI.RedDotType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

