
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.item
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class Item : Luban.BeanBase
{
    public Item(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Count = _buf.ReadInt();
        Quality = (item.EItemQuality)_buf.ReadInt();
        TestQuality = (item.TestEItemQuality)_buf.ReadInt();
        TestValFloat = _buf.ReadFloat();
        TestValBool = _buf.ReadBool();
        TestValShort = _buf.ReadShort();
        TestValLong = _buf.ReadLong();
        TestValDouble = _buf.ReadDouble();
        TestValV2 = global::cfg.vector2.Deserializevector2(_buf);
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);List1 = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); List1.Add(_e0);}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Array1 = new item.Reward[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { item.Reward __e0;__e0 = global::cfg.item.Reward.DeserializeReward(_buf); Array1[__index0] = __e0;}}
    }

    public static Item DeserializeItem(ByteBuf _buf)
    {
        return new item.Item(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 个数
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly item.EItemQuality Quality;
    /// <summary>
    /// 品质2
    /// </summary>
    public readonly item.TestEItemQuality TestQuality;
    /// <summary>
    /// 浮点测试
    /// </summary>
    public readonly float TestValFloat;
    /// <summary>
    /// 布尔测试
    /// </summary>
    public readonly bool TestValBool;
    /// <summary>
    /// Short测试
    /// </summary>
    public readonly short TestValShort;
    /// <summary>
    /// Long测试
    /// </summary>
    public readonly long TestValLong;
    /// <summary>
    /// double测试
    /// </summary>
    public readonly double TestValDouble;
    /// <summary>
    /// 自定义类型V2测试
    /// </summary>
    public readonly vector2 TestValV2;
    /// <summary>
    /// 自定义类型Arr2
    /// </summary>
    public readonly System.Collections.Generic.List<int> List1;
    public readonly item.Reward[] Array1;
   
    public const int __ID__ = 2107285806;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Array1) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "count:" + Count + ","
        + "quality:" + Quality + ","
        + "testQuality:" + TestQuality + ","
        + "testValFloat:" + TestValFloat + ","
        + "testValBool:" + TestValBool + ","
        + "testValShort:" + TestValShort + ","
        + "testValLong:" + TestValLong + ","
        + "testValDouble:" + TestValDouble + ","
        + "testValV2:" + TestValV2 + ","
        + "list1:" + Luban.StringUtil.CollectionToString(List1) + ","
        + "array1:" + Luban.StringUtil.CollectionToString(Array1) + ","
        + "}";
    }
}
}

