
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.item
{
/// <summary>
/// 奖励
/// </summary>

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class Reward : Luban.BeanBase
{
    public Reward(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
    }

    public static Reward DeserializeReward(ByteBuf _buf)
    {
        return new item.Reward(_buf);
    }

    /// <summary>
    /// 奖励道具ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 奖励道具名称
    /// </summary>
    public readonly string Name;
   
    public const int __ID__ = -1878566262;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "}";
    }
}
}

