
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.item
{ 
    public enum TestEItemQuality
    {
        /// <summary>
        /// 白
        /// </summary>
        WHITE = 1,
        /// <summary>
        /// 黑
        /// </summary>
        GREEN = 2,
        /// <summary>
        /// 蓝
        /// </summary>
        BLUE = 3,
    }

} 

