// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cs.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameProto {

  /// <summary>Holder for reflection information generated from cs.proto</summary>
  public static partial class CsReflection {

    #region Descriptor
    /// <summary>File descriptor for cs.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cghjcy5wcm90bxIMeW91cl9wYWNrYWdlIqwBCg5Dc1JvbGVMb2dpblJlcRIL",
            "CgN1aW4YASABKA0SDQoFdG9rZW4YAiABKAkSEAoIaW9SVFNWZXIYAyABKAUS",
            "EgoKYWxpQ2hhbm5lbBgEIAEoCRIRCgl0aW1lc3RhbXAYBSABKAMSDAoEc2ln",
            "bhgGIAEoCRIQCghkZXZpY2VJZBgHIAEoCRIRCglvc1ZlcnNpb24YCCABKAkS",
            "EgoKYXBwVmVyc2lvbhgJIAEoCSLIAQoOQ3NSb2xlTG9naW5SZXMSJwoEc3Vj",
            "YxgBIAEoDjIZLnlvdXJfcGFja2FnZS5Dc0Vycm9yQ29kZRIQCghzdnJfdGlt",
            "ZRgCIAEoAxISCgpzdnJfb2Zmc2V0GAQgASgFEg0KBUlzTmV3GAUgASgIEhcK",
            "D2lzQ3JlYXRlTmV3Um9sZRgGIAEoCBISCgpuZXdXb3JsZElkGAcgASgFEhAK",
            "CGVycm9yTXNnGAggASgJEhkKEXJldHJ5QWZ0ZXJTZWNvbmRzGAkgASgFIjIK",
            "D0NzS2lja091dE5vdGlmeRIOCgZyZWFzb24YASABKAUSDwoHbWVzc2FnZRgC",
            "IAEoCSqOAQoJQ3NNc2dUeXBlEhEKDVNFU1NJT05fQlJFQUsQABISCg5TRVNT",
            "SU9OX0FDQ0VQVBABEhUKEVNFU1NJT05fT05MSU5FTlVNEAISFwoSTVNHX1JP",
            "TEVfTE9HSU5fUkVREOgHEhcKEk1TR19ST0xFX0xPR0lOX1JFUxDpBxIRCgxN",
            "U0dfS0lDS19PVVQQ6gcqoQIKC0NzRXJyb3JDb2RlEhEKDUVSUl9DT0RFX1NV",
            "Q0MQABIaChZFUlJfQ09ERV9JTlZBTElEX1BBUkFNEAESGgoWRVJSX0NPREVf",
            "SU5WQUxJRF9UT0tFThACEhoKFkVSUl9DT0RFX1RPS0VOX0VYUElSRUQQAxIb",
            "ChdFUlJfQ09ERV9BQ0NPVU5UX0JBTk5FRBAEEhsKF0VSUl9DT0RFX0FMUkVB",
            "RFlfT05MSU5FEAUSGQoVRVJSX0NPREVfU0VSVkVSX0VSUk9SEAYSHgoaRVJS",
            "X0NPREVfVElNRVNUQU1QX0lOVkFMSUQQBxIZChVFUlJfQ09ERV9TSUdOX0lO",
            "VkFMSUQQCBIbChdFUlJfQ09ERV9UT09fTUFOWV9GQUlMUxAJQgyqAglHYW1l",
            "UHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameProto.CsMsgType), typeof(global::GameProto.CsErrorCode), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProto.CsRoleLoginReq), global::GameProto.CsRoleLoginReq.Parser, new[]{ "Uin", "Token", "IoRTSVer", "AliChannel", "Timestamp", "Sign", "DeviceId", "OsVersion", "AppVersion" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProto.CsRoleLoginRes), global::GameProto.CsRoleLoginRes.Parser, new[]{ "Succ", "SvrTime", "SvrOffset", "IsNew", "IsCreateNewRole", "NewWorldId", "ErrorMsg", "RetryAfterSeconds" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProto.CsKickOutNotify), global::GameProto.CsKickOutNotify.Parser, new[]{ "Reason", "Message" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///************************枚举第一个值必须是0*********************
  /// 消息类型
  /// </summary>
  public enum CsMsgType {
    /// <summary>
    /// 服务器自留
    /// </summary>
    [pbr::OriginalName("SESSION_BREAK")] SessionBreak = 0,
    [pbr::OriginalName("SESSION_ACCEPT")] SessionAccept = 1,
    [pbr::OriginalName("SESSION_ONLINENUM")] SessionOnlinenum = 2,
    /// <summary>
    /// 双端交互
    /// </summary>
    [pbr::OriginalName("MSG_ROLE_LOGIN_REQ")] MsgRoleLoginReq = 1000,
    /// <summary>
    /// CsRoleLoginRes
    /// </summary>
    [pbr::OriginalName("MSG_ROLE_LOGIN_RES")] MsgRoleLoginRes = 1001,
    /// <summary>
    /// CsKickOutNotify 踢出通知
    /// </summary>
    [pbr::OriginalName("MSG_KICK_OUT")] MsgKickOut = 1002,
  }

  public enum CsErrorCode {
    /// <summary>
    /// 成功
    /// </summary>
    [pbr::OriginalName("ERR_CODE_SUCC")] ErrCodeSucc = 0,
    /// <summary>
    /// 参数错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_INVALID_PARAM")] ErrCodeInvalidParam = 1,
    /// <summary>
    /// Token无效
    /// </summary>
    [pbr::OriginalName("ERR_CODE_INVALID_TOKEN")] ErrCodeInvalidToken = 2,
    /// <summary>
    /// Token过期
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TOKEN_EXPIRED")] ErrCodeTokenExpired = 3,
    /// <summary>
    /// 账号封禁
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ACCOUNT_BANNED")] ErrCodeAccountBanned = 4,
    /// <summary>
    /// 账号已在线
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ALREADY_ONLINE")] ErrCodeAlreadyOnline = 5,
    /// <summary>
    /// 服务器内部错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_SERVER_ERROR")] ErrCodeServerError = 6,
    /// <summary>
    /// 时间戳无效
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TIMESTAMP_INVALID")] ErrCodeTimestampInvalid = 7,
    /// <summary>
    /// 签名验证失败
    /// </summary>
    [pbr::OriginalName("ERR_CODE_SIGN_INVALID")] ErrCodeSignInvalid = 8,
    /// <summary>
    /// 登录失败次数过多
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TOO_MANY_FAILS")] ErrCodeTooManyFails = 9,
  }

  #endregion

  #region Messages
  public sealed partial class CsRoleLoginReq : pb::IMessage<CsRoleLoginReq> {
    private static readonly pb::MessageParser<CsRoleLoginReq> _parser = new pb::MessageParser<CsRoleLoginReq>(() => new CsRoleLoginReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CsRoleLoginReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProto.CsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CsRoleLoginReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CsRoleLoginReq(CsRoleLoginReq other) : this() {
      uin_ = other.uin_;
      token_ = other.token_;
      ioRTSVer_ = other.ioRTSVer_;
      aliChannel_ = other.aliChannel_;
      timestamp_ = other.timestamp_;
      sign_ = other.sign_;
      deviceId_ = other.deviceId_;
      osVersion_ = other.osVersion_;
      appVersion_ = other.appVersion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CsRoleLoginReq Clone() {
      return new CsRoleLoginReq(this);
    }

    /// <summary>Field number for the "uin" field.</summary>
    public const int UinFieldNumber = 1;
    private uint uin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Uin {
      get { return uin_; }
      set {
        uin_ = value;
      }
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 2;
    private string token_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ioRTSVer" field.</summary>
    public const int IoRTSVerFieldNumber = 3;
    private int ioRTSVer_;
    /// <summary>
    /// ioRTS版本
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IoRTSVer {
      get { return ioRTSVer_; }
      set {
        ioRTSVer_ = value;
      }
    }

    /// <summary>Field number for the "aliChannel" field.</summary>
    public const int AliChannelFieldNumber = 4;
    private string aliChannel_ = "";
    /// <summary>
    /// 支小用户来源
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AliChannel {
      get { return aliChannel_; }
      set {
        aliChannel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 5;
    private long timestamp_;
    /// <summary>
    /// 客户端时间戳（毫秒）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "sign" field.</summary>
    public const int SignFieldNumber = 6;
    private string sign_ = "";
    /// <summary>
    /// 签名（防篡改）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sign {
      get { return sign_; }
      set {
        sign_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "deviceId" field.</summary>
    public const int DeviceIdFieldNumber = 7;
    private string deviceId_ = "";
    /// <summary>
    /// 设备ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DeviceId {
      get { return deviceId_; }
      set {
        deviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "osVersion" field.</summary>
    public const int OsVersionFieldNumber = 8;
    private string osVersion_ = "";
    /// <summary>
    /// 操作系统版本
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OsVersion {
      get { return osVersion_; }
      set {
        osVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "appVersion" field.</summary>
    public const int AppVersionFieldNumber = 9;
    private string appVersion_ = "";
    /// <summary>
    /// 应用版本
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AppVersion {
      get { return appVersion_; }
      set {
        appVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CsRoleLoginReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CsRoleLoginReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uin != other.Uin) return false;
      if (Token != other.Token) return false;
      if (IoRTSVer != other.IoRTSVer) return false;
      if (AliChannel != other.AliChannel) return false;
      if (Timestamp != other.Timestamp) return false;
      if (Sign != other.Sign) return false;
      if (DeviceId != other.DeviceId) return false;
      if (OsVersion != other.OsVersion) return false;
      if (AppVersion != other.AppVersion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Uin != 0) hash ^= Uin.GetHashCode();
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (IoRTSVer != 0) hash ^= IoRTSVer.GetHashCode();
      if (AliChannel.Length != 0) hash ^= AliChannel.GetHashCode();
      if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
      if (Sign.Length != 0) hash ^= Sign.GetHashCode();
      if (DeviceId.Length != 0) hash ^= DeviceId.GetHashCode();
      if (OsVersion.Length != 0) hash ^= OsVersion.GetHashCode();
      if (AppVersion.Length != 0) hash ^= AppVersion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Uin != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Uin);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Token);
      }
      if (IoRTSVer != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(IoRTSVer);
      }
      if (AliChannel.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AliChannel);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Timestamp);
      }
      if (Sign.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Sign);
      }
      if (DeviceId.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(DeviceId);
      }
      if (OsVersion.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(OsVersion);
      }
      if (AppVersion.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(AppVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Uin != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Uin);
      }
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (IoRTSVer != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IoRTSVer);
      }
      if (AliChannel.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AliChannel);
      }
      if (Timestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      if (Sign.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sign);
      }
      if (DeviceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceId);
      }
      if (OsVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OsVersion);
      }
      if (AppVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppVersion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CsRoleLoginReq other) {
      if (other == null) {
        return;
      }
      if (other.Uin != 0) {
        Uin = other.Uin;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      if (other.IoRTSVer != 0) {
        IoRTSVer = other.IoRTSVer;
      }
      if (other.AliChannel.Length != 0) {
        AliChannel = other.AliChannel;
      }
      if (other.Timestamp != 0L) {
        Timestamp = other.Timestamp;
      }
      if (other.Sign.Length != 0) {
        Sign = other.Sign;
      }
      if (other.DeviceId.Length != 0) {
        DeviceId = other.DeviceId;
      }
      if (other.OsVersion.Length != 0) {
        OsVersion = other.OsVersion;
      }
      if (other.AppVersion.Length != 0) {
        AppVersion = other.AppVersion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Uin = input.ReadUInt32();
            break;
          }
          case 18: {
            Token = input.ReadString();
            break;
          }
          case 24: {
            IoRTSVer = input.ReadInt32();
            break;
          }
          case 34: {
            AliChannel = input.ReadString();
            break;
          }
          case 40: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 50: {
            Sign = input.ReadString();
            break;
          }
          case 58: {
            DeviceId = input.ReadString();
            break;
          }
          case 66: {
            OsVersion = input.ReadString();
            break;
          }
          case 74: {
            AppVersion = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CsRoleLoginRes : pb::IMessage<CsRoleLoginRes> {
    private static readonly pb::MessageParser<CsRoleLoginRes> _parser = new pb::MessageParser<CsRoleLoginRes>(() => new CsRoleLoginRes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CsRoleLoginRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProto.CsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CsRoleLoginRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CsRoleLoginRes(CsRoleLoginRes other) : this() {
      succ_ = other.succ_;
      svrTime_ = other.svrTime_;
      svrOffset_ = other.svrOffset_;
      isNew_ = other.isNew_;
      isCreateNewRole_ = other.isCreateNewRole_;
      newWorldId_ = other.newWorldId_;
      errorMsg_ = other.errorMsg_;
      retryAfterSeconds_ = other.retryAfterSeconds_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CsRoleLoginRes Clone() {
      return new CsRoleLoginRes(this);
    }

    /// <summary>Field number for the "succ" field.</summary>
    public const int SuccFieldNumber = 1;
    private global::GameProto.CsErrorCode succ_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProto.CsErrorCode Succ {
      get { return succ_; }
      set {
        succ_ = value;
      }
    }

    /// <summary>Field number for the "svr_time" field.</summary>
    public const int SvrTimeFieldNumber = 2;
    private long svrTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long SvrTime {
      get { return svrTime_; }
      set {
        svrTime_ = value;
      }
    }

    /// <summary>Field number for the "svr_offset" field.</summary>
    public const int SvrOffsetFieldNumber = 4;
    private int svrOffset_;
    /// <summary>
    /// 时区偏移信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SvrOffset {
      get { return svrOffset_; }
      set {
        svrOffset_ = value;
      }
    }

    /// <summary>Field number for the "IsNew" field.</summary>
    public const int IsNewFieldNumber = 5;
    private bool isNew_;
    /// <summary>
    /// 新用户
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsNew {
      get { return isNew_; }
      set {
        isNew_ = value;
      }
    }

    /// <summary>Field number for the "isCreateNewRole" field.</summary>
    public const int IsCreateNewRoleFieldNumber = 6;
    private bool isCreateNewRole_;
    /// <summary>
    /// 是否创建新角色
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsCreateNewRole {
      get { return isCreateNewRole_; }
      set {
        isCreateNewRole_ = value;
      }
    }

    /// <summary>Field number for the "newWorldId" field.</summary>
    public const int NewWorldIdFieldNumber = 7;
    private int newWorldId_;
    /// <summary>
    /// 新角色的世界id； isCreateNewRole=true时有效
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int NewWorldId {
      get { return newWorldId_; }
      set {
        newWorldId_ = value;
      }
    }

    /// <summary>Field number for the "errorMsg" field.</summary>
    public const int ErrorMsgFieldNumber = 8;
    private string errorMsg_ = "";
    /// <summary>
    /// 错误描述信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ErrorMsg {
      get { return errorMsg_; }
      set {
        errorMsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "retryAfterSeconds" field.</summary>
    public const int RetryAfterSecondsFieldNumber = 9;
    private int retryAfterSeconds_;
    /// <summary>
    /// 失败后多少秒可重试
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RetryAfterSeconds {
      get { return retryAfterSeconds_; }
      set {
        retryAfterSeconds_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CsRoleLoginRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CsRoleLoginRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Succ != other.Succ) return false;
      if (SvrTime != other.SvrTime) return false;
      if (SvrOffset != other.SvrOffset) return false;
      if (IsNew != other.IsNew) return false;
      if (IsCreateNewRole != other.IsCreateNewRole) return false;
      if (NewWorldId != other.NewWorldId) return false;
      if (ErrorMsg != other.ErrorMsg) return false;
      if (RetryAfterSeconds != other.RetryAfterSeconds) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Succ != 0) hash ^= Succ.GetHashCode();
      if (SvrTime != 0L) hash ^= SvrTime.GetHashCode();
      if (SvrOffset != 0) hash ^= SvrOffset.GetHashCode();
      if (IsNew != false) hash ^= IsNew.GetHashCode();
      if (IsCreateNewRole != false) hash ^= IsCreateNewRole.GetHashCode();
      if (NewWorldId != 0) hash ^= NewWorldId.GetHashCode();
      if (ErrorMsg.Length != 0) hash ^= ErrorMsg.GetHashCode();
      if (RetryAfterSeconds != 0) hash ^= RetryAfterSeconds.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Succ != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Succ);
      }
      if (SvrTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SvrTime);
      }
      if (SvrOffset != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SvrOffset);
      }
      if (IsNew != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsNew);
      }
      if (IsCreateNewRole != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsCreateNewRole);
      }
      if (NewWorldId != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(NewWorldId);
      }
      if (ErrorMsg.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ErrorMsg);
      }
      if (RetryAfterSeconds != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(RetryAfterSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Succ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Succ);
      }
      if (SvrTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SvrTime);
      }
      if (SvrOffset != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SvrOffset);
      }
      if (IsNew != false) {
        size += 1 + 1;
      }
      if (IsCreateNewRole != false) {
        size += 1 + 1;
      }
      if (NewWorldId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NewWorldId);
      }
      if (ErrorMsg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMsg);
      }
      if (RetryAfterSeconds != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RetryAfterSeconds);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CsRoleLoginRes other) {
      if (other == null) {
        return;
      }
      if (other.Succ != 0) {
        Succ = other.Succ;
      }
      if (other.SvrTime != 0L) {
        SvrTime = other.SvrTime;
      }
      if (other.SvrOffset != 0) {
        SvrOffset = other.SvrOffset;
      }
      if (other.IsNew != false) {
        IsNew = other.IsNew;
      }
      if (other.IsCreateNewRole != false) {
        IsCreateNewRole = other.IsCreateNewRole;
      }
      if (other.NewWorldId != 0) {
        NewWorldId = other.NewWorldId;
      }
      if (other.ErrorMsg.Length != 0) {
        ErrorMsg = other.ErrorMsg;
      }
      if (other.RetryAfterSeconds != 0) {
        RetryAfterSeconds = other.RetryAfterSeconds;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            succ_ = (global::GameProto.CsErrorCode) input.ReadEnum();
            break;
          }
          case 16: {
            SvrTime = input.ReadInt64();
            break;
          }
          case 32: {
            SvrOffset = input.ReadInt32();
            break;
          }
          case 40: {
            IsNew = input.ReadBool();
            break;
          }
          case 48: {
            IsCreateNewRole = input.ReadBool();
            break;
          }
          case 56: {
            NewWorldId = input.ReadInt32();
            break;
          }
          case 66: {
            ErrorMsg = input.ReadString();
            break;
          }
          case 72: {
            RetryAfterSeconds = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 踢出通知
  /// </summary>
  public sealed partial class CsKickOutNotify : pb::IMessage<CsKickOutNotify> {
    private static readonly pb::MessageParser<CsKickOutNotify> _parser = new pb::MessageParser<CsKickOutNotify>(() => new CsKickOutNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CsKickOutNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProto.CsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CsKickOutNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CsKickOutNotify(CsKickOutNotify other) : this() {
      reason_ = other.reason_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CsKickOutNotify Clone() {
      return new CsKickOutNotify(this);
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 1;
    private int reason_;
    /// <summary>
    /// 踢出原因（1=重复登录，2=账号封禁）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Reason {
      get { return reason_; }
      set {
        reason_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    /// <summary>
    /// 提示信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CsKickOutNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CsKickOutNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Reason != other.Reason) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Reason != 0) hash ^= Reason.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Reason != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Reason);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Reason != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Reason);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CsKickOutNotify other) {
      if (other == null) {
        return;
      }
      if (other.Reason != 0) {
        Reason = other.Reason;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Reason = input.ReadInt32();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
