
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Map
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class MapData : Luban.BeanBase
{
    public MapData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Random = _buf.ReadBool();
        Birth = global::cfg.Fix2.DeserializeFix2(_buf);
        Music = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);PlatformDataId = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); PlatformDataId.Add(_e0);}}
    }

    public static MapData DeserializeMapData(ByteBuf _buf)
    {
        return new Map.MapData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 资源
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 是否随机地图
    /// </summary>
    public readonly bool Random;
    /// <summary>
    /// 出生点
    /// </summary>
    public readonly Fix2 Birth;
    /// <summary>
    /// 地图音乐
    /// </summary>
    public readonly string Music;
    /// <summary>
    /// 动态平台生成数据
    /// </summary>
    public readonly System.Collections.Generic.List<int> PlatformDataId;
   
    public const int __ID__ = 1981076564;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Birth?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "random:" + Random + ","
        + "birth:" + Birth + ","
        + "music:" + Music + ","
        + "PlatformDataId:" + Luban.StringUtil.CollectionToString(PlatformDataId) + ","
        + "}";
    }
}
}

