
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Map
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class PlatformDef : Luban.BeanBase
{
    public PlatformDef(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        StartX = global::cfg.Fix.DeserializeFix(_buf);
        StartY = global::cfg.Fix.DeserializeFix(_buf);
        EndX = global::cfg.Fix.DeserializeFix(_buf);
        EndY = global::cfg.Fix.DeserializeFix(_buf);
        Speed = global::cfg.Fix.DeserializeFix(_buf);
        HalfWidth = global::cfg.Fix.DeserializeFix(_buf);
        HalfHeight = global::cfg.Fix.DeserializeFix(_buf);
        AssetPath = _buf.ReadString();
    }

    public static PlatformDef DeserializePlatformDef(ByteBuf _buf)
    {
        return new Map.PlatformDef(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 开始点
    /// </summary>
    public readonly Fix StartX;
    /// <summary>
    /// 开始点
    /// </summary>
    public readonly Fix StartY;
    /// <summary>
    /// 结束点
    /// </summary>
    public readonly Fix EndX;
    /// <summary>
    /// 结束点
    /// </summary>
    public readonly Fix EndY;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly Fix Speed;
    /// <summary>
    /// 宽度
    /// </summary>
    public readonly Fix HalfWidth;
    /// <summary>
    /// 高度
    /// </summary>
    public readonly Fix HalfHeight;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly string AssetPath;
   
    public const int __ID__ = 89095360;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        StartX?.ResolveRef(tables);
        StartY?.ResolveRef(tables);
        EndX?.ResolveRef(tables);
        EndY?.ResolveRef(tables);
        Speed?.ResolveRef(tables);
        HalfWidth?.ResolveRef(tables);
        HalfHeight?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "StartX:" + StartX + ","
        + "StartY:" + StartY + ","
        + "EndX:" + EndX + ","
        + "EndY:" + EndY + ","
        + "Speed:" + Speed + ","
        + "HalfWidth:" + HalfWidth + ","
        + "HalfHeight:" + HalfHeight + ","
        + "AssetPath:" + AssetPath + ","
        + "}";
    }
}
}

