
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Map
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public partial class TbMapData:Tables.IVOFun
{
    private readonly System.Collections.Generic.Dictionary<int, Map.MapData> _dataMap;
    private readonly System.Collections.Generic.List<Map.MapData> _dataList;
    
    public TbMapData()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Map.MapData>();
        _dataList = new System.Collections.Generic.List<Map.MapData>();
    }	
	
	public void _LoadData(ByteBuf _buf)
    {
       for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Map.MapData _v;
            _v = global::cfg.Map.MapData.DeserializeMapData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Map.MapData> DataMap => _dataMap;
    public System.Collections.Generic.List<Map.MapData> DataList => _dataList;

    public Map.MapData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Map.MapData Get(int key) => _dataMap[key];
    public Map.MapData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

