
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Map
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public partial class TbPlatformDef:Tables.IVOFun
{
    private readonly System.Collections.Generic.Dictionary<int, Map.PlatformDef> _dataMap;
    private readonly System.Collections.Generic.List<Map.PlatformDef> _dataList;
    
    public TbPlatformDef()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Map.PlatformDef>();
        _dataList = new System.Collections.Generic.List<Map.PlatformDef>();
    }	
	
	public void _LoadData(ByteBuf _buf)
    {
       for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Map.PlatformDef _v;
            _v = global::cfg.Map.PlatformDef.DeserializePlatformDef(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Map.PlatformDef> DataMap => _dataMap;
    public System.Collections.Generic.List<Map.PlatformDef> DataList => _dataList;

    public Map.PlatformDef GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Map.PlatformDef Get(int key) => _dataMap[key];
    public Map.PlatformDef this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

