
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class Fix : Luban.BeanBase
{
    public Fix(ByteBuf _buf) 
    {
        Val = _buf.ReadInt();
    }

    public static Fix DeserializeFix(ByteBuf _buf)
    {
        return new Fix(_buf);
    }

    /// <summary>
    /// 坐标
    /// </summary>
    public readonly int Val;
   
    public const int __ID__ = 70645;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "val:" + Val + ","
        + "}";
    }
}
}

