
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class Localization : Luban.BeanBase
{
    public Localization(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        ChineseSimplified = _buf.ReadString();
        ChineseTraditional = _buf.ReadString();
        English = _buf.ReadString();
    }

    public static Localization DeserializeLocalization(ByteBuf _buf)
    {
        return new Localization(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 简中
    /// </summary>
    public readonly string ChineseSimplified;
    /// <summary>
    /// 繁中
    /// </summary>
    public readonly string ChineseTraditional;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string English;
   
    public const int __ID__ = -647685447;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "ChineseSimplified:" + ChineseSimplified + ","
        + "ChineseTraditional:" + ChineseTraditional + ","
        + "English:" + English + ","
        + "}";
    }
}
}

