
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class SingleAnimInfo : Luban.BeanBase
{
    public SingleAnimInfo(ByteBuf _buf) 
    {
        AnimName = _buf.ReadString();
        Duration = global::cfg.Fix.DeserializeFix(_buf);
    }

    public static SingleAnimInfo DeserializeSingleAnimInfo(ByteBuf _buf)
    {
        return new SingleAnimInfo(_buf);
    }

    /// <summary>
    /// animator中的名称
    /// </summary>
    public readonly string AnimName;
    /// <summary>
    /// 在多久之后权重清0，单位秒
    /// </summary>
    public readonly Fix Duration;
   
    public const int __ID__ = -1486612761;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Duration?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "animName:" + AnimName + ","
        + "duration:" + Duration + ","
        + "}";
    }
}
}

