
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;
namespace cfg
{
#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public partial class Tables
{
    public interface IVOFun
    {
        void _LoadData(ByteBuf data);

        void ResolveRef(Tables tables);
    }

    public Dictionary<string, IVOFun> CfgDic = new Dictionary<string, IVOFun>();

	public const string tblocalization = "tblocalization";
	public const string ui_tbgamemodule = "ui_tbgamemodule";
	public const string ui_tbreddot = "ui_tbreddot";
	public const string ai_tbaigroupdef = "ai_tbaigroupdef";
	public const string ai_tbaiactiondef = "ai_tbaiactiondef";
	public const string anim_tbanimgroup = "anim_tbanimgroup";
	public const string anim_tbanimdef = "anim_tbanimdef";
	public const string chapter_tbmainchapter = "chapter_tbmainchapter";
	public const string core_tbsoundgrouptable = "core_tbsoundgrouptable";
	public const string core_tbuigrouptable = "core_tbuigrouptable";
	public const string core_tbentitygrouptable = "core_tbentitygrouptable";
	public const string entity_tbmonster = "entity_tbmonster";
	public const string entity_tbhero = "entity_tbhero";
	public const string item_tbitem = "item_tbitem";
	public const string map_tbmapdata = "map_tbmapdata";
	public const string map_tbplatformdef = "map_tbplatformdef";
	public const string skill_tbbuffdef = "skill_tbbuffdef";
	public const string skill_tbaoedef = "skill_tbaoedef";
	public const string skill_tbskillaoedef = "skill_tbskillaoedef";
	public const string skill_tbskillbulletdef = "skill_tbskillbulletdef";
	public const string skill_tbbulletdef = "skill_tbbulletdef";
	public const string skill_tbskilldef = "skill_tbskilldef";
	public const string skill_tbtimelinedef = "skill_tbtimelinedef";
	public const string spawner_tbmonsterspawner = "spawner_tbmonsterspawner";
		
    public Tables()
    {
		  CfgDic.Add("tblocalization",new TbLocalization());
		  CfgDic.Add("ui_tbgamemodule",new UI.TbGameModule());
		  CfgDic.Add("ui_tbreddot",new UI.TbRedDot());
		  CfgDic.Add("ai_tbaigroupdef",new AI.TbAIGroupDef());
		  CfgDic.Add("ai_tbaiactiondef",new AI.TbAIActionDef());
		  CfgDic.Add("anim_tbanimgroup",new Anim.TbAnimGroup());
		  CfgDic.Add("anim_tbanimdef",new Anim.TbAnimDef());
		  CfgDic.Add("chapter_tbmainchapter",new Chapter.TbMainChapter());
		  CfgDic.Add("core_tbsoundgrouptable",new Core.TbSoundGroupTable());
		  CfgDic.Add("core_tbuigrouptable",new Core.TbUIGroupTable());
		  CfgDic.Add("core_tbentitygrouptable",new Core.TbEntityGroupTable());
		  CfgDic.Add("entity_tbmonster",new Entity.TbMonster());
		  CfgDic.Add("entity_tbhero",new Entity.TbHero());
		  CfgDic.Add("item_tbitem",new item.TbItem());
		  CfgDic.Add("map_tbmapdata",new Map.TbMapData());
		  CfgDic.Add("map_tbplatformdef",new Map.TbPlatformDef());
		  CfgDic.Add("skill_tbbuffdef",new Skill.TbBuffDef());
		  CfgDic.Add("skill_tbaoedef",new Skill.TbAoeDef());
		  CfgDic.Add("skill_tbskillaoedef",new Skill.TbSkillAoeDef());
		  CfgDic.Add("skill_tbskillbulletdef",new Skill.TbSkillBulletDef());
		  CfgDic.Add("skill_tbbulletdef",new Skill.TbBulletDef());
		  CfgDic.Add("skill_tbskilldef",new Skill.TbSkillDef());
		  CfgDic.Add("skill_tbtimelinedef",new Skill.TbTimeLineDef());
		  CfgDic.Add("spawner_tbmonsterspawner",new Spawner.TbMonsterSpawner());
    }    
}

}
