
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public partial class TbLocalization:Tables.IVOFun
{
    private readonly System.Collections.Generic.Dictionary<string, Localization> _dataMap;
    private readonly System.Collections.Generic.List<Localization> _dataList;
    
    public TbLocalization()
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Localization>();
        _dataList = new System.Collections.Generic.List<Localization>();
    }	
	
	public void _LoadData(ByteBuf _buf)
    {
       for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Localization _v;
            _v = global::cfg.Localization.DeserializeLocalization(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Localization> DataMap => _dataMap;
    public System.Collections.Generic.List<Localization> DataList => _dataList;

    public Localization GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Localization Get(string key) => _dataMap[key];
    public Localization this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

