
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class AoeDef : Luban.BeanBase
{
    public AoeDef(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Prefab = _buf.ReadString();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Tags = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); Tags[__index0] = __e0;}}
        TickTime = global::cfg.Fix.DeserializeFix(_buf);
        RemoveOnObstacle = _buf.ReadBool();
        if(_buf.ReadBool()){ OnCreate = global::cfg.Skill.AoeEvent.DeserializeAoeEvent(_buf); } else { OnCreate = null; }
        if(_buf.ReadBool()){ OnRemoved = global::cfg.Skill.AoeEvent.DeserializeAoeEvent(_buf); } else { OnRemoved = null; }
        if(_buf.ReadBool()){ OnTick = global::cfg.Skill.AoeEvent.DeserializeAoeEvent(_buf); } else { OnTick = null; }
        if(_buf.ReadBool()){ OnChaEnter = global::cfg.Skill.AoeEvent.DeserializeAoeEvent(_buf); } else { OnChaEnter = null; }
        if(_buf.ReadBool()){ OnChaLeave = global::cfg.Skill.AoeEvent.DeserializeAoeEvent(_buf); } else { OnChaLeave = null; }
        if(_buf.ReadBool()){ OnBulletEnter = global::cfg.Skill.AoeEvent.DeserializeAoeEvent(_buf); } else { OnBulletEnter = null; }
        if(_buf.ReadBool()){ OnBulletLeave = global::cfg.Skill.AoeEvent.DeserializeAoeEvent(_buf); } else { OnBulletLeave = null; }
    }

    public static AoeDef DeserializeAoeDef(ByteBuf _buf)
    {
        return new Skill.AoeDef(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 预制体名字
    /// </summary>
    public readonly string Prefab;
    /// <summary>
    /// aoe的tag
    /// </summary>
    public readonly string[] Tags;
    /// <summary>
    /// aoe每一跳的时间，单位：秒
    /// </summary>
    public readonly Fix TickTime;
    /// <summary>
    /// aoe是否碰撞到阻挡就摧毁了（removed），如果不是，移动就是smooth的，如果移动的话……
    /// </summary>
    public readonly bool RemoveOnObstacle;
    /// <summary>
    /// aoe创建时的事件
    /// </summary>
    public readonly Skill.AoeEvent OnCreate;
    /// <summary>
    /// aoe结束时的事件
    /// </summary>
    public readonly Skill.AoeEvent OnRemoved;
    /// <summary>
    /// oe每一跳的事件，如果没有，就不会发生每一跳
    /// </summary>
    public readonly Skill.AoeEvent OnTick;
    /// <summary>
    /// 有角色进入aoe时的事件，onCreate时候位于aoe范围内的人不会触发这个，但是在onCreate里面会已经存在
    /// </summary>
    public readonly Skill.AoeEvent OnChaEnter;
    /// <summary>
    /// 有角色离开aoe结束时的事件
    /// </summary>
    public readonly Skill.AoeEvent OnChaLeave;
    /// <summary>
    /// 有子弹进入aoe时的事件，onCreate时候位于aoe范围内的子弹不会触发这个，但是在onCreate里面会已经存在
    /// </summary>
    public readonly Skill.AoeEvent OnBulletEnter;
    /// <summary>
    /// 有子弹进入aoe时的事件，onCreate时候位于aoe范围内的子弹不会触发这个，但是在onCreate里面会已经存在
    /// </summary>
    public readonly Skill.AoeEvent OnBulletLeave;
   
    public const int __ID__ = 1119963403;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        TickTime?.ResolveRef(tables);
        OnCreate?.ResolveRef(tables);
        OnRemoved?.ResolveRef(tables);
        OnTick?.ResolveRef(tables);
        OnChaEnter?.ResolveRef(tables);
        OnChaLeave?.ResolveRef(tables);
        OnBulletEnter?.ResolveRef(tables);
        OnBulletLeave?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "prefab:" + Prefab + ","
        + "tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "tickTime:" + TickTime + ","
        + "removeOnObstacle:" + RemoveOnObstacle + ","
        + "onCreate:" + OnCreate + ","
        + "onRemoved:" + OnRemoved + ","
        + "onTick:" + OnTick + ","
        + "onChaEnter:" + OnChaEnter + ","
        + "onChaLeave:" + OnChaLeave + ","
        + "onBulletEnter:" + OnBulletEnter + ","
        + "onBulletLeave:" + OnBulletLeave + ","
        + "}";
    }
}
}

