
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class ApplyForceToCaster : Skill.TimeLineDefParam
{
    public ApplyForceToCaster(ByteBuf _buf)  : base(_buf) 
    {
        Speed = global::cfg.Fix.DeserializeFix(_buf);
        Duration = global::cfg.Fix.DeserializeFix(_buf);
        CanMoveInput = _buf.ReadBool();
        VerticalSpeed = global::cfg.Fix.DeserializeFix(_buf);
    }

    public static ApplyForceToCaster DeserializeApplyForceToCaster(ByteBuf _buf)
    {
        return new Skill.ApplyForceToCaster(_buf);
    }

    /// <summary>
    /// 冲刺速度（精度1000，如18000=18米/秒），方向自动跟随Caster朝向
    /// </summary>
    public readonly Fix Speed;
    /// <summary>
    /// 推力持续时长（秒，精度1000，如180=0.18秒）
    /// </summary>
    public readonly Fix Duration;
    /// <summary>
    /// 冲刺期间是否允许移动输入覆盖（false=锁移动方向，true=可叠加输入）
    /// </summary>
    public readonly bool CanMoveInput;
    /// <summary>
    /// 竖向速度（精度1000，如10000=10米/秒），非0时直接设置竖向速度用于跳跃，0则不影响竖向
    /// </summary>
    public readonly Fix VerticalSpeed;
   
    public const int __ID__ = -1077680959;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Speed?.ResolveRef(tables);
        Duration?.ResolveRef(tables);
        VerticalSpeed?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "time:" + Time + ","
        + "Speed:" + Speed + ","
        + "Duration:" + Duration + ","
        + "CanMoveInput:" + CanMoveInput + ","
        + "VerticalSpeed:" + VerticalSpeed + ","
        + "}";
    }
}
}

