
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{
/// <summary>
/// Buff附加状态
/// </summary>

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class BuffAddState : Luban.BeanBase
{
    public BuffAddState(ByteBuf _buf) 
    {
        CanMove = _buf.ReadBool();
        CanRotate = _buf.ReadBool();
        CanUseSkill = _buf.ReadBool();
    }

    public static BuffAddState DeserializeBuffAddState(ByteBuf _buf)
    {
        return new Skill.BuffAddState(_buf);
    }

    /// <summary>
    /// 是否能移动
    /// </summary>
    public readonly bool CanMove;
    /// <summary>
    /// 是否能旋转
    /// </summary>
    public readonly bool CanRotate;
    /// <summary>
    /// 是否能使用技能
    /// </summary>
    public readonly bool CanUseSkill;
   
    public const int __ID__ = 791594656;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "canMove:" + CanMove + ","
        + "canRotate:" + CanRotate + ","
        + "canUseSkill:" + CanUseSkill + ","
        + "}";
    }
}
}

