
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class BuffDef : Luban.BeanBase
{
    public BuffDef(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Tag = new Skill.BuffTag[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { Skill.BuffTag __e0;__e0 = (Skill.BuffTag)_buf.ReadInt(); Tag[__index0] = __e0;}}
        Priority = _buf.ReadInt();
        Permanent = _buf.ReadBool();
        Duration = global::cfg.Fix.DeserializeFix(_buf);
        MaxStack = _buf.ReadInt();
        TickTime = _buf.ReadFloat();
        if(_buf.ReadBool()){ OnOccur = global::cfg.Skill.BuffEvent.DeserializeBuffEvent(_buf); } else { OnOccur = null; }
        if(_buf.ReadBool()){ OnRemoved = global::cfg.Skill.BuffEvent.DeserializeBuffEvent(_buf); } else { OnRemoved = null; }
        if(_buf.ReadBool()){ OnTick = global::cfg.Skill.BuffEvent.DeserializeBuffEvent(_buf); } else { OnTick = null; }
        if(_buf.ReadBool()){ OnCast = global::cfg.Skill.BuffEvent.DeserializeBuffEvent(_buf); } else { OnCast = null; }
        if(_buf.ReadBool()){ OnHit = global::cfg.Skill.BuffEvent.DeserializeBuffEvent(_buf); } else { OnHit = null; }
        if(_buf.ReadBool()){ BeHurt = global::cfg.Skill.BuffEvent.DeserializeBuffEvent(_buf); } else { BeHurt = null; }
        if(_buf.ReadBool()){ OnKill = global::cfg.Skill.BuffEvent.DeserializeBuffEvent(_buf); } else { OnKill = null; }
        if(_buf.ReadBool()){ BeKilled = global::cfg.Skill.BuffEvent.DeserializeBuffEvent(_buf); } else { BeKilled = null; }
        BuffAddState = global::cfg.Skill.BuffAddState.DeserializeBuffAddState(_buf);
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BuffPropMod = new Skill.BuffPropMod[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { Skill.BuffPropMod __e0;__e0 = global::cfg.Skill.BuffPropMod.DeserializeBuffPropMod(_buf); BuffPropMod[__index0] = __e0;}}
    }

    public static BuffDef DeserializeBuffDef(ByteBuf _buf)
    {
        return new Skill.BuffDef(_buf);
    }

    /// <summary>
    /// Buff编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Buff标签
    /// </summary>
    public readonly Skill.BuffTag[] Tag;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 是否永久
    /// </summary>
    public readonly bool Permanent;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly Fix Duration;
    /// <summary>
    /// 最大层数
    /// </summary>
    public readonly int MaxStack;
    /// <summary>
    /// 每秒调用
    /// </summary>
    public readonly float TickTime;
    /// <summary>
    /// buff在被添加、改变层数时候触发的事件
    /// </summary>
    public readonly Skill.BuffEvent OnOccur;
    /// <summary>
    /// 在这个buffObj被移除之前要做的事情，如果运行之后buffObj又不足以被删除了就会被保留
    /// </summary>
    public readonly Skill.BuffEvent OnRemoved;
    /// <summary>
    /// buff在每个工作周期会执行的函数，如果这个函数为空，或者tickTime&lt;=0，都不会发生周期性工作
    /// </summary>
    public readonly Skill.BuffEvent OnTick;
    /// <summary>
    /// 在释放技能的时候运行的buff，执行这个buff获得最终技能要产生的Timeline
    /// </summary>
    public readonly Skill.BuffEvent OnCast;
    /// <summary>
    /// 在伤害流程中，持有这个buff的人作为攻击者会发生的事情
    /// </summary>
    public readonly Skill.BuffEvent OnHit;
    /// <summary>
    /// 在伤害流程中，持有这个buff的人作为挨打者会发生的事情
    /// </summary>
    public readonly Skill.BuffEvent BeHurt;
    /// <summary>
    /// 在伤害流程中，如果击杀目标，则会触发的啥事情
    /// </summary>
    public readonly Skill.BuffEvent OnKill;
    /// <summary>
    /// 伤害流程中，持有这个buff的人被杀死了，会触发的事情
    /// </summary>
    public readonly Skill.BuffEvent BeKilled;
    /// <summary>
    /// Buff附加的状态
    /// </summary>
    public readonly Skill.BuffAddState BuffAddState;
    /// <summary>
    /// buff造成的属性修改
    /// </summary>
    public readonly Skill.BuffPropMod[] BuffPropMod;
   
    public const int __ID__ = 1420310485;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Duration?.ResolveRef(tables);
        OnOccur?.ResolveRef(tables);
        OnRemoved?.ResolveRef(tables);
        OnTick?.ResolveRef(tables);
        OnCast?.ResolveRef(tables);
        OnHit?.ResolveRef(tables);
        BeHurt?.ResolveRef(tables);
        OnKill?.ResolveRef(tables);
        BeKilled?.ResolveRef(tables);
        BuffAddState?.ResolveRef(tables);
        foreach (var _e in BuffPropMod) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "tag:" + Luban.StringUtil.CollectionToString(Tag) + ","
        + "priority:" + Priority + ","
        + "permanent:" + Permanent + ","
        + "duration:" + Duration + ","
        + "maxStack:" + MaxStack + ","
        + "tickTime:" + TickTime + ","
        + "onOccur:" + OnOccur + ","
        + "onRemoved:" + OnRemoved + ","
        + "onTick:" + OnTick + ","
        + "onCast:" + OnCast + ","
        + "onHit:" + OnHit + ","
        + "beHurt:" + BeHurt + ","
        + "onKill:" + OnKill + ","
        + "beKilled:" + BeKilled + ","
        + "buffAddState:" + BuffAddState + ","
        + "buffPropMod:" + Luban.StringUtil.CollectionToString(BuffPropMod) + ","
        + "}";
    }
}
}

