
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public abstract partial class BuffEvent : Luban.BeanBase
{
    public BuffEvent(ByteBuf _buf) 
    {
    }

    public static BuffEvent DeserializeBuffEvent(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case Skill.ReloadAmmo.__ID__: return new Skill.ReloadAmmo(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

