
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{
/// <summary>
/// Buff附加属性
/// </summary>

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class BuffPropMod : Luban.BeanBase
{
    public BuffPropMod(ByteBuf _buf) 
    {
        Hp = _buf.ReadInt();
        Attack = _buf.ReadInt();
        MoveSpeed = _buf.ReadInt();
        ActionSpeed = _buf.ReadInt();
        Ammo = _buf.ReadInt();
        BodyRadius = global::cfg.Fix.DeserializeFix(_buf);
        HitRadius = global::cfg.Fix.DeserializeFix(_buf);
    }

    public static BuffPropMod DeserializeBuffPropMod(ByteBuf _buf)
    {
        return new Skill.BuffPropMod(_buf);
    }

    /// <summary>
    /// 最大生命，基本都得有，哪怕角色只有1，装备可以是0
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 移动速度，他不是米/秒作为单位的，而是一个可以培养的数值。
    /// </summary>
    public readonly int MoveSpeed;
    /// <summary>
    /// 行动速度，和移动速度不同，他是增加角色行动速度，也就是变化timeline和动画播放的scale的，比如wow里面开嗜血就是加行动速度
    /// </summary>
    public readonly int ActionSpeed;
    /// <summary>
    /// 其实相当于mp了
    /// </summary>
    public readonly int Ammo;
    /// <summary>
    /// 用于移动碰撞的，单位：米
    /// </summary>
    public readonly Fix BodyRadius;
    /// <summary>
    /// 同体型圆形，只是用途不同，用在判断子弹是否命中的时候
    /// </summary>
    public readonly Fix HitRadius;
   
    public const int __ID__ = 1696266351;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        BodyRadius?.ResolveRef(tables);
        HitRadius?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "hp:" + Hp + ","
        + "attack:" + Attack + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "actionSpeed:" + ActionSpeed + ","
        + "ammo:" + Ammo + ","
        + "bodyRadius:" + BodyRadius + ","
        + "hitRadius:" + HitRadius + ","
        + "}";
    }
}
}

