
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public abstract partial class BulletTweenParam : Luban.BeanBase
{
    public BulletTweenParam(ByteBuf _buf) 
    {
    }

    public static BulletTweenParam DeserializeBulletTweenParam(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case Skill.GrenadeTween.__ID__: return new Skill.GrenadeTween(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

