
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public abstract partial class BulletEventParam : Luban.BeanBase
{
    public BulletEventParam(ByteBuf _buf) 
    {
    }

    public static BulletEventParam DeserializeBulletEventParam(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case Skill.RecordBullet.__ID__: return new Skill.RecordBullet(_buf);
            case Skill.CommonBulletHit.__ID__: return new Skill.CommonBulletHit(_buf);
            case Skill.CommonBulletRemoved.__ID__: return new Skill.CommonBulletRemoved(_buf);
            case Skill.GrenadeCreate.__ID__: return new Skill.GrenadeCreate(_buf);
            case Skill.GrenadeRemoved.__ID__: return new Skill.GrenadeRemoved(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

