
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class BulletDef : Luban.BeanBase
{
    public BulletDef(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Prefab = _buf.ReadString();
        if(_buf.ReadBool()){ OnCreate = global::cfg.Skill.BulletEventParam.DeserializeBulletEventParam(_buf); } else { OnCreate = null; }
        if(_buf.ReadBool()){ OnHit = global::cfg.Skill.BulletEventParam.DeserializeBulletEventParam(_buf); } else { OnHit = null; }
        if(_buf.ReadBool()){ OnRemoved = global::cfg.Skill.BulletEventParam.DeserializeBulletEventParam(_buf); } else { OnRemoved = null; }
        if(_buf.ReadBool()){ TweenParam = global::cfg.Skill.BulletTweenParam.DeserializeBulletTweenParam(_buf); } else { TweenParam = null; }
        Radius = global::cfg.Fix.DeserializeFix(_buf);
        HitTimes = _buf.ReadInt();
        SameTargetDelay = global::cfg.Fix.DeserializeFix(_buf);
        MoveType = (Game.MoveType)_buf.ReadInt();
        RemoveOnObstacle = _buf.ReadBool();
        HitAlly = _buf.ReadBool();
        HitFoe = _buf.ReadBool();
        UseWorldSpaceTween = _buf.ReadBool();
        SmoothMove = _buf.ReadBool();
    }

    public static BulletDef DeserializeBulletDef(ByteBuf _buf)
    {
        return new Skill.BulletDef(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 预制体名字
    /// </summary>
    public readonly string Prefab;
    /// <summary>
    /// 子弹被创建的事件
    /// </summary>
    public readonly Skill.BulletEventParam OnCreate;
    /// <summary>
    /// 子弹命中目标时候发生的事情
    /// </summary>
    public readonly Skill.BulletEventParam OnHit;
    /// <summary>
    /// 子弹生命周期结束时候发生的事情
    /// </summary>
    public readonly Skill.BulletEventParam OnRemoved;
    /// <summary>
    /// 移动轨迹
    /// </summary>
    public readonly Skill.BulletTweenParam TweenParam;
    /// <summary>
    /// 子弹的碰撞半径，单位：米。这个游戏里子弹在逻辑世界都是圆形的，当然是这个游戏设定如此，实际策划的需求未必只能是圆形。
    /// </summary>
    public readonly Fix Radius;
    /// <summary>
    /// 子弹可以碰触的次数，每次碰到合理目标-1，到0的时候子弹就结束了。
    /// </summary>
    public readonly int HitTimes;
    /// <summary>
    /// 弹碰触同一个目标的延迟，单位：秒，最小值是Time.fixedDeltaTime（每帧发生一次）
    /// </summary>
    public readonly Fix SameTargetDelay;
    /// <summary>
    /// 子弹的移动方式，一般来说都是飞行的，也有部分是手雷这种属于走路的
    /// </summary>
    public readonly Game.MoveType MoveType;
    /// <summary>
    /// 子弹的是否碰到障碍物就爆炸，不会的话会沿着障碍物移动
    /// </summary>
    public readonly bool RemoveOnObstacle;
    /// <summary>
    /// /子弹是否会命中盟军
    /// </summary>
    public readonly bool HitAlly;
    /// <summary>
    /// 子弹是否会命中敌人
    /// </summary>
    public readonly bool HitFoe;
    public readonly bool UseWorldSpaceTween;
    public readonly bool SmoothMove;
   
    public const int __ID__ = 351499270;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        OnCreate?.ResolveRef(tables);
        OnHit?.ResolveRef(tables);
        OnRemoved?.ResolveRef(tables);
        TweenParam?.ResolveRef(tables);
        Radius?.ResolveRef(tables);
        SameTargetDelay?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "prefab:" + Prefab + ","
        + "onCreate:" + OnCreate + ","
        + "onHit:" + OnHit + ","
        + "onRemoved:" + OnRemoved + ","
        + "tweenParam:" + TweenParam + ","
        + "radius:" + Radius + ","
        + "hitTimes:" + HitTimes + ","
        + "sameTargetDelay:" + SameTargetDelay + ","
        + "moveType:" + MoveType + ","
        + "removeOnObstacle:" + RemoveOnObstacle + ","
        + "hitAlly:" + HitAlly + ","
        + "hitFoe:" + HitFoe + ","
        + "useWorldSpaceTween:" + UseWorldSpaceTween + ","
        + "smoothMove:" + SmoothMove + ","
        + "}";
    }
}
}

