
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class CasterPlayAnim : Skill.TimeLineDefParam
{
    public CasterPlayAnim(ByteBuf _buf)  : base(_buf) 
    {
        AnimType = (Anim.Type)_buf.ReadInt();
        UseCurrentDeg = _buf.ReadBool();
    }

    public static CasterPlayAnim DeserializeCasterPlayAnim(ByteBuf _buf)
    {
        return new Skill.CasterPlayAnim(_buf);
    }

    /// <summary>
    /// 是要播放的动画
    /// </summary>
    public readonly Anim.Type AnimType;
    /// <summary>
    /// 如果false或者缺省了，就代表启用timelineObj中储存的（开始时的）
    /// </summary>
    public readonly bool UseCurrentDeg;
   
    public const int __ID__ = 1250260270;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "time:" + Time + ","
        + "animType:" + AnimType + ","
        + "useCurrentDeg:" + UseCurrentDeg + ","
        + "}";
    }
}
}

