
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class CommonBulletRemoved : Skill.BulletEventParam
{
    public CommonBulletRemoved(ByteBuf _buf)  : base(_buf) 
    {
        SightEffect = _buf.ReadString();
    }

    public static CommonBulletRemoved DeserializeCommonBulletRemoved(ByteBuf _buf)
    {
        return new Skill.CommonBulletRemoved(_buf);
    }

    /// <summary>
    /// 命中视觉特效
    /// </summary>
    public readonly string SightEffect;
   
    public const int __ID__ = -618011274;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "sightEffect:" + SightEffect + ","
        + "}";
    }
}
}

