
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class CommonBulletHit : Skill.BulletEventParam
{
    public CommonBulletHit(ByteBuf _buf)  : base(_buf) 
    {
        DamageTimes = global::cfg.Fix.DeserializeFix(_buf);
        CritRate = global::cfg.Fix.DeserializeFix(_buf);
        SightEffect = _buf.ReadString();
        BpName = _buf.ReadString();
    }

    public static CommonBulletHit DeserializeCommonBulletHit(ByteBuf _buf)
    {
        return new Skill.CommonBulletHit(_buf);
    }

    /// <summary>
    /// 伤害倍数
    /// </summary>
    public readonly Fix DamageTimes;
    /// <summary>
    /// 基础暴击率
    /// </summary>
    public readonly Fix CritRate;
    /// <summary>
    /// 命中视觉特效
    /// </summary>
    public readonly string SightEffect;
    /// <summary>
    /// 播放特效位于目标的绑点，默认Body
    /// </summary>
    public readonly string BpName;
   
    public const int __ID__ = 1342528425;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        DamageTimes?.ResolveRef(tables);
        CritRate?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "damageTimes:" + DamageTimes + ","
        + "critRate:" + CritRate + ","
        + "sightEffect:" + SightEffect + ","
        + "bpName:" + BpName + ","
        + "}";
    }
}
}

