
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class CreateAoeSightEffect : Skill.AoeEvent
{
    public CreateAoeSightEffect(ByteBuf _buf)  : base(_buf) 
    {
        SightEffect = _buf.ReadString();
    }

    public static CreateAoeSightEffect DeserializeCreateAoeSightEffect(ByteBuf _buf)
    {
        return new Skill.CreateAoeSightEffect(_buf);
    }

    /// <summary>
    /// 特效
    /// </summary>
    public readonly string SightEffect;
   
    public const int __ID__ = 407480048;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "sightEffect:" + SightEffect + ","
        + "}";
    }
}
}

