
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class DoDamageToCreate : Skill.AoeEvent
{
    public DoDamageToCreate(ByteBuf _buf)  : base(_buf) 
    {
        BaseDamage = _buf.ReadInt();
        DamageTimes = global::cfg.Fix.DeserializeFix(_buf);
        ToFoe = _buf.ReadBool();
        ToAlly = _buf.ReadBool();
        HurtAction = _buf.ReadBool();
        Effect = _buf.ReadString();
        BpName = _buf.ReadString();
    }

    public static DoDamageToCreate DeserializeDoDamageToCreate(ByteBuf _buf)
    {
        return new Skill.DoDamageToCreate(_buf);
    }

    /// <summary>
    /// 基础伤害
    /// </summary>
    public readonly int BaseDamage;
    /// <summary>
    /// 施法者攻击倍率
    /// </summary>
    public readonly Fix DamageTimes;
    /// <summary>
    /// 对敌人有效
    /// </summary>
    public readonly bool ToFoe;
    /// <summary>
    /// 对盟军有效
    /// </summary>
    public readonly bool ToAlly;
    /// <summary>
    /// 挨打的人是否受伤动作
    /// </summary>
    public readonly bool HurtAction;
    /// <summary>
    /// 挨打者身上特效
    /// </summary>
    public readonly string Effect;
    /// <summary>
    /// 挨打者特效绑点，默认&quot;Body&quot;
    /// </summary>
    public readonly string BpName;
   
    public const int __ID__ = 1248265102;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        DamageTimes?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "baseDamage:" + BaseDamage + ","
        + "damageTimes:" + DamageTimes + ","
        + "toFoe:" + ToFoe + ","
        + "toAlly:" + ToAlly + ","
        + "hurtAction:" + HurtAction + ","
        + "effect:" + Effect + ","
        + "bpName:" + BpName + ","
        + "}";
    }
}
}

