
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class FireBullet : Skill.TimeLineDefParam
{
    public FireBullet(ByteBuf _buf)  : base(_buf) 
    {
        BulletDataId = _buf.ReadInt();
    }

    public static FireBullet DeserializeFireBullet(ByteBuf _buf)
    {
        return new Skill.FireBullet(_buf);
    }

    /// <summary>
    /// 子弹数据，见bulletDef表
    /// </summary>
    public readonly int BulletDataId;
   
    public const int __ID__ = 684576469;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "time:" + Time + ","
        + "BulletDataId:" + BulletDataId + ","
        + "}";
    }
}
}

