
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class GrenadeRemoved : Skill.BulletEventParam
{
    public GrenadeRemoved(ByteBuf _buf)  : base(_buf) 
    {
        ExplosionSkillAoeId = _buf.ReadInt();
    }

    public static GrenadeRemoved DeserializeGrenadeRemoved(ByteBuf _buf)
    {
        return new Skill.GrenadeRemoved(_buf);
    }

    public readonly int ExplosionSkillAoeId;
   
    public const int __ID__ = -15798097;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ExplosionSkillAoeId:" + ExplosionSkillAoeId + ","
        + "}";
    }
}
}

