
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class GrenadeTween : Skill.BulletTweenParam
{
    public GrenadeTween(ByteBuf _buf)  : base(_buf) 
    {
        Gravity = global::cfg.Fix.DeserializeFix(_buf);
        BounceCoeff = global::cfg.Fix.DeserializeFix(_buf);
        GroundFriction = global::cfg.Fix.DeserializeFix(_buf);
        MaxBounces = _buf.ReadInt();
        WallBounceCoeff = global::cfg.Fix.DeserializeFix(_buf);
    }

    public static GrenadeTween DeserializeGrenadeTween(ByteBuf _buf)
    {
        return new Skill.GrenadeTween(_buf);
    }

    public readonly Fix Gravity;
    public readonly Fix BounceCoeff;
    public readonly Fix GroundFriction;
    public readonly int MaxBounces;
    public readonly Fix WallBounceCoeff;
   
    public const int __ID__ = 1119676026;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Gravity?.ResolveRef(tables);
        BounceCoeff?.ResolveRef(tables);
        GroundFriction?.ResolveRef(tables);
        WallBounceCoeff?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Gravity:" + Gravity + ","
        + "BounceCoeff:" + BounceCoeff + ","
        + "GroundFriction:" + GroundFriction + ","
        + "MaxBounces:" + MaxBounces + ","
        + "WallBounceCoeff:" + WallBounceCoeff + ","
        + "}";
    }
}
}

