
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Skill
{ 
    public enum Operator
    {
        /// <summary>
        /// 大于
        /// </summary>
        GT = 1,
        /// <summary>
        /// 小于
        /// </summary>
        LT = 2,
        /// <summary>
        /// 大于等于
        /// </summary>
        GE = 3,
        /// <summary>
        /// 小于等于
        /// </summary>
        LE = 4,
        /// <summary>
        /// 不等于
        /// </summary>
        NE = 5,
        /// <summary>
        /// 等于
        /// </summary>
        EQ = 6,
    }

} 

