
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class PlaySightEffectOnCaster : Skill.TimeLineDefParam
{
    public PlaySightEffectOnCaster(ByteBuf _buf)  : base(_buf) 
    {
        BindPointKey = _buf.ReadString();
        EffectName = _buf.ReadString();
        EffectKey = _buf.ReadString();
        Loop = _buf.ReadBool();
    }

    public static PlaySightEffectOnCaster DeserializePlaySightEffectOnCaster(ByteBuf _buf)
    {
        return new Skill.PlaySightEffectOnCaster(_buf);
    }

    /// <summary>
    /// 要播放特效的绑点
    /// </summary>
    public readonly string BindPointKey;
    /// <summary>
    /// 位于Prafabs/下
    /// </summary>
    public readonly string EffectName;
    /// <summary>
    /// 用于删除的
    /// </summary>
    public readonly string EffectKey;
    /// <summary>
    /// 循环就要手动删除
    /// </summary>
    public readonly bool Loop;
   
    public const int __ID__ = 1376229864;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "time:" + Time + ","
        + "bindPointKey:" + BindPointKey + ","
        + "effectName:" + EffectName + ","
        + "effectKey:" + EffectKey + ","
        + "loop:" + Loop + ","
        + "}";
    }
}
}

