
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class PlaySound : Skill.TimeLineDefParam
{
    public PlaySound(ByteBuf _buf)  : base(_buf) 
    {
        SoundName = _buf.ReadString();
        Only = _buf.ReadBool();
        Interval = global::cfg.Fix.DeserializeFix(_buf);
    }

    public static PlaySound DeserializePlaySound(ByteBuf _buf)
    {
        return new Skill.PlaySound(_buf);
    }

    /// <summary>
    /// 音效名字
    /// </summary>
    public readonly string SoundName;
    /// <summary>
    /// 是否唯一
    /// </summary>
    public readonly bool Only;
    /// <summary>
    /// 当为唯一时，多少秒后才能重新播放
    /// </summary>
    public readonly Fix Interval;
   
    public const int __ID__ = 1494364830;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Interval?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "time:" + Time + ","
        + "SoundName:" + SoundName + ","
        + "Only:" + Only + ","
        + "Interval:" + Interval + ","
        + "}";
    }
}
}

