
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Skill
{ 
    public enum PropertyType
    {
        /// <summary>
        /// 血量
        /// </summary>
        HP = 1,
        /// <summary>
        /// 攻击
        /// </summary>
        ATK = 2,
        /// <summary>
        /// 防御
        /// </summary>
        DEF = 3,
    }

} 

