
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class RecordBullet : Skill.BulletEventParam
{
    public RecordBullet(ByteBuf _buf)  : base(_buf) 
    {
    }

    public static RecordBullet DeserializeRecordBullet(ByteBuf _buf)
    {
        return new Skill.RecordBullet(_buf);
    }

   
    public const int __ID__ = 1601829232;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

