
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{
/// <summary>
/// 资源
/// </summary>

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class Resource : Luban.BeanBase
{
    public Resource(ByteBuf _buf) 
    {
        Hp = _buf.ReadInt();
        Ammo = _buf.ReadInt();
        Stamina = _buf.ReadInt();
    }

    public static Resource DeserializeResource(ByteBuf _buf)
    {
        return new Skill.Resource(_buf);
    }

    /// <summary>
    /// 血量
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 弹药
    /// </summary>
    public readonly int Ammo;
    /// <summary>
    /// 耐力
    /// </summary>
    public readonly int Stamina;
   
    public const int __ID__ = -2033047733;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "hp:" + Hp + ","
        + "ammo:" + Ammo + ","
        + "stamina:" + Stamina + ","
        + "}";
    }
}
}

