
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class SetCasterControlState : Skill.TimeLineDefParam
{
    public SetCasterControlState(ByteBuf _buf)  : base(_buf) 
    {
        CanMove = _buf.ReadBool();
        CanRotate = _buf.ReadBool();
        CanUseSkill = _buf.ReadBool();
    }

    public static SetCasterControlState DeserializeSetCasterControlState(ByteBuf _buf)
    {
        return new Skill.SetCasterControlState(_buf);
    }

    /// <summary>
    /// 是否能移动
    /// </summary>
    public readonly bool CanMove;
    /// <summary>
    /// 是否能旋转
    /// </summary>
    public readonly bool CanRotate;
    /// <summary>
    /// 是否能使用技能
    /// </summary>
    public readonly bool CanUseSkill;
   
    public const int __ID__ = 267178853;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "time:" + Time + ","
        + "canMove:" + CanMove + ","
        + "canRotate:" + CanRotate + ","
        + "canUseSkill:" + CanUseSkill + ","
        + "}";
    }
}
}

