
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class SkillDef : Luban.BeanBase
{
    public SkillDef(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Cost = global::cfg.Skill.Resource.DeserializeResource(_buf);
        Condition = global::cfg.Skill.Resource.DeserializeResource(_buf);
        TimeLine = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AddBuff = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AddBuff.Add(_e0);}}
    }

    public static SkillDef DeserializeSkillDef(ByteBuf _buf)
    {
        return new Skill.SkillDef(_buf);
    }

    /// <summary>
    /// 技能编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 使用消耗
    /// </summary>
    public readonly Skill.Resource Cost;
    /// <summary>
    /// 使用条件
    /// </summary>
    public readonly Skill.Resource Condition;
    /// <summary>
    /// timeLine编号
    /// </summary>
    public readonly int TimeLine;
    /// <summary>
    /// Buff编号
    /// </summary>
    public readonly System.Collections.Generic.List<int> AddBuff;
   
    public const int __ID__ = 450443057;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Cost?.ResolveRef(tables);
        Condition?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "cost:" + Cost + ","
        + "condition:" + Condition + ","
        + "timeLine:" + TimeLine + ","
        + "addBuff:" + Luban.StringUtil.CollectionToString(AddBuff) + ","
        + "}";
    }
}
}

