
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class SkillAoeDef : Luban.BeanBase
{
    public SkillAoeDef(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AoeDataId = _buf.ReadInt();
        Position = global::cfg.Fix3.DeserializeFix3(_buf);
        Radius = global::cfg.Fix.DeserializeFix(_buf);
        Duration = global::cfg.Fix.DeserializeFix(_buf);
        Degree = global::cfg.Fix.DeserializeFix(_buf);
    }

    public static SkillAoeDef DeserializeSkillAoeDef(ByteBuf _buf)
    {
        return new Skill.SkillAoeDef(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// AOE数据（见AoeDef)
    /// </summary>
    public readonly int AoeDataId;
    /// <summary>
    /// 生成的坐标，y轴是无效的
    /// </summary>
    public readonly Fix3 Position;
    /// <summary>
    /// aoe的半径，单位：米
    /// </summary>
    public readonly Fix Radius;
    /// <summary>
    /// aoe存在的时间，单位：秒
    /// </summary>
    public readonly Fix Duration;
    /// <summary>
    /// aoe的角度（360是圆形）
    /// </summary>
    public readonly Fix Degree;
   
    public const int __ID__ = 1594664930;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Position?.ResolveRef(tables);
        Radius?.ResolveRef(tables);
        Duration?.ResolveRef(tables);
        Degree?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "aoeDataId:" + AoeDataId + ","
        + "position:" + Position + ","
        + "radius:" + Radius + ","
        + "duration:" + Duration + ","
        + "degree:" + Degree + ","
        + "}";
    }
}
}

