
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class SkillBulletDef : Luban.BeanBase
{
    public SkillBulletDef(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        BulletData = _buf.ReadInt();
        FirePos = global::cfg.Fix3.DeserializeFix3(_buf);
        Degree = global::cfg.Fix.DeserializeFix(_buf);
        Speed = global::cfg.Fix.DeserializeFix(_buf);
        Duration = global::cfg.Fix.DeserializeFix(_buf);
    }

    public static SkillBulletDef DeserializeSkillBulletDef(ByteBuf _buf)
    {
        return new Skill.SkillBulletDef(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 子弹数据（见bulletDef)
    /// </summary>
    public readonly int BulletData;
    /// <summary>
    /// 发射的坐标，y轴是无效的
    /// </summary>
    public readonly Fix3 FirePos;
    /// <summary>
    /// 发射的角度，单位：角度
    /// </summary>
    public readonly Fix Degree;
    /// <summary>
    /// 子弹的初速度，单位：米/秒
    /// </summary>
    public readonly Fix Speed;
    /// <summary>
    /// 子弹的生命周期，单位：秒
    /// </summary>
    public readonly Fix Duration;
   
    public const int __ID__ = -1142615601;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        FirePos?.ResolveRef(tables);
        Degree?.ResolveRef(tables);
        Speed?.ResolveRef(tables);
        Duration?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "bulletData:" + BulletData + ","
        + "firePos:" + FirePos + ","
        + "degree:" + Degree + ","
        + "speed:" + Speed + ","
        + "duration:" + Duration + ","
        + "}";
    }
}
}

