
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public partial class TbBuffDef:Tables.IVOFun
{
    private readonly System.Collections.Generic.Dictionary<int, Skill.BuffDef> _dataMap;
    private readonly System.Collections.Generic.List<Skill.BuffDef> _dataList;
    
    public TbBuffDef()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Skill.BuffDef>();
        _dataList = new System.Collections.Generic.List<Skill.BuffDef>();
    }	
	
	public void _LoadData(ByteBuf _buf)
    {
       for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Skill.BuffDef _v;
            _v = global::cfg.Skill.BuffDef.DeserializeBuffDef(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Skill.BuffDef> DataMap => _dataMap;
    public System.Collections.Generic.List<Skill.BuffDef> DataList => _dataList;

    public Skill.BuffDef GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Skill.BuffDef Get(int key) => _dataMap[key];
    public Skill.BuffDef this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

