
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public partial class TbBulletDef:Tables.IVOFun
{
    private readonly System.Collections.Generic.Dictionary<int, Skill.BulletDef> _dataMap;
    private readonly System.Collections.Generic.List<Skill.BulletDef> _dataList;
    
    public TbBulletDef()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Skill.BulletDef>();
        _dataList = new System.Collections.Generic.List<Skill.BulletDef>();
    }	
	
	public void _LoadData(ByteBuf _buf)
    {
       for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Skill.BulletDef _v;
            _v = global::cfg.Skill.BulletDef.DeserializeBulletDef(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Skill.BulletDef> DataMap => _dataMap;
    public System.Collections.Generic.List<Skill.BulletDef> DataList => _dataList;

    public Skill.BulletDef GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Skill.BulletDef Get(int key) => _dataMap[key];
    public Skill.BulletDef this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

