
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{
/// <summary>
/// 技能时间线节点
/// </summary>

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public abstract partial class TimeLineDefParam : Luban.BeanBase
{
    public TimeLineDefParam(ByteBuf _buf) 
    {
        Time = global::cfg.Fix.DeserializeFix(_buf);
    }

    public static TimeLineDefParam DeserializeTimeLineDefParam(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case Skill.SetCasterControlState.__ID__: return new Skill.SetCasterControlState(_buf);
            case Skill.CasterPlayAnim.__ID__: return new Skill.CasterPlayAnim(_buf);
            case Skill.PlaySightEffectOnCaster.__ID__: return new Skill.PlaySightEffectOnCaster(_buf);
            case Skill.FireBullet.__ID__: return new Skill.FireBullet(_buf);
            case Skill.UseAoeToPoint.__ID__: return new Skill.UseAoeToPoint(_buf);
            case Skill.PlaySound.__ID__: return new Skill.PlaySound(_buf);
            case Skill.ApplyForceToCaster.__ID__: return new Skill.ApplyForceToCaster(_buf);
            default: throw new SerializationException();
        }
    }

    /// <summary>
    /// 时间点
    /// </summary>
    public readonly Fix Time;
   

    public virtual void ResolveRef(Tables tables)
    {
        Time?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "time:" + Time + ","
        + "}";
    }
}
}

