
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class TimeLineDef : Luban.BeanBase
{
    public TimeLineDef(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TimeLineParams = new System.Collections.Generic.List<Skill.TimeLineDefParam>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Skill.TimeLineDefParam _e0;  _e0 = global::cfg.Skill.TimeLineDefParam.DeserializeTimeLineDefParam(_buf); TimeLineParams.Add(_e0);}}
        Duration = global::cfg.Fix.DeserializeFix(_buf);
    }

    public static TimeLineDef DeserializeTimeLineDef(ByteBuf _buf)
    {
        return new Skill.TimeLineDef(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 时间线节点
    /// </summary>
    public readonly System.Collections.Generic.List<Skill.TimeLineDefParam> TimeLineParams;
    /// <summary>
    /// 持续
    /// </summary>
    public readonly Fix Duration;
   
    public const int __ID__ = 750015367;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in TimeLineParams) { _e?.ResolveRef(tables); }
        Duration?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "timeLineParams:" + Luban.StringUtil.CollectionToString(TimeLineParams) + ","
        + "duration:" + Duration + ","
        + "}";
    }
}
}

