
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Skill
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class UseAoeToPoint : Skill.TimeLineDefParam
{
    public UseAoeToPoint(ByteBuf _buf)  : base(_buf) 
    {
        SkillAoeId = _buf.ReadInt();
    }

    public static UseAoeToPoint DeserializeUseAoeToPoint(ByteBuf _buf)
    {
        return new Skill.UseAoeToPoint(_buf);
    }

    /// <summary>
    /// 子弹数据，见SkillAoeDef表
    /// </summary>
    public readonly int SkillAoeId;
   
    public const int __ID__ = 1662662056;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "time:" + Time + ","
        + "SkillAoeId:" + SkillAoeId + ","
        + "}";
    }
}
}

