
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Anim
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public sealed partial class AnimDef : Luban.BeanBase
{
    public AnimDef(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Priority = _buf.ReadInt();
        Type = (Anim.Type)_buf.ReadInt();
        Direction = (Anim.Direction)_buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Sub = new SingleAnimInfo[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { SingleAnimInfo __e0;__e0 = global::cfg.SingleAnimInfo.DeserializeSingleAnimInfo(_buf); Sub[__index0] = __e0;}}
    }

    public static AnimDef DeserializeAnimDef(ByteBuf _buf)
    {
        return new Anim.AnimDef(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 动画类型
    /// </summary>
    public readonly Anim.Type Type;
    /// <summary>
    /// 朝向
    /// </summary>
    public readonly Anim.Direction Direction;
    /// <summary>
    /// 动画列表，为什么是数组，比如随机播放3个受动画,就是随机其中1个
    /// </summary>
    public readonly SingleAnimInfo[] Sub;
   
    public const int __ID__ = 473751895;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Sub) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "priority:" + Priority + ","
        + "type:" + Type + ","
        + "direction:" + Direction + ","
        + "sub:" + Luban.StringUtil.CollectionToString(Sub) + ","
        + "}";
    }
}
}

