
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Anim
{ 
    public enum Direction
    {
        /// <summary>
        /// 上
        /// </summary>
        Top = 90,
        /// <summary>
        /// 右上
        /// </summary>
        RightTop = 35,
        /// <summary>
        /// 右
        /// </summary>
        Right = 0,
        /// <summary>
        /// 右下
        /// </summary>
        RightBottom = 330,
        /// <summary>
        /// 下
        /// </summary>
        Bottom = 270,
        /// <summary>
        /// 左下
        /// </summary>
        LeftBottom = 215,
        /// <summary>
        /// 左
        /// </summary>
        Left = 180,
        /// <summary>
        /// 左上
        /// </summary>
        LeftTop = 150,
        Null = 999,
    }

} 

