
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Anim
{

#if ENABLE_OBFUZ
[Obfuz.ObfuzIgnore(Obfuz.ObfuzScope.TypeName | Obfuz.ObfuzScope.MethodName)]
#endif
public partial class TbAnimGroup:Tables.IVOFun
{
    private readonly System.Collections.Generic.Dictionary<int, Anim.AnimGroup> _dataMap;
    private readonly System.Collections.Generic.List<Anim.AnimGroup> _dataList;
    
    public TbAnimGroup()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Anim.AnimGroup>();
        _dataList = new System.Collections.Generic.List<Anim.AnimGroup>();
    }	
	
	public void _LoadData(ByteBuf _buf)
    {
       for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Anim.AnimGroup _v;
            _v = global::cfg.Anim.AnimGroup.DeserializeAnimGroup(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Anim.AnimGroup> DataMap => _dataMap;
    public System.Collections.Generic.List<Anim.AnimGroup> DataList => _dataList;

    public Anim.AnimGroup GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Anim.AnimGroup Get(int key) => _dataMap[key];
    public Anim.AnimGroup this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

