
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Anim
{ 
    public enum Type
    {
        Null = 1,
        /// <summary>
        /// 等待
        /// </summary>
        Idle = 2,
        /// <summary>
        /// 跑
        /// </summary>
        Run = 3,
        /// <summary>
        /// 攻击
        /// </summary>
        Atk = 4,
        /// <summary>
        /// 受伤
        /// </summary>
        TakeDamage = 5,
        /// <summary>
        /// 跳
        /// </summary>
        Jump = 6,
        /// <summary>
        /// 下落
        /// </summary>
        Fall = 7,
        /// <summary>
        /// 贴墙
        /// </summary>
        WallSlide = 8,
        /// <summary>
        /// 冲刺
        /// </summary>
        Dash = 9,
    }

} 

